### ISSUE TITLE
Flow Sensitive analysis seems broken within loops

### ISSUE THREAD

**Issue by thierry-tct** [mchalupa/dg#118]
when printing dependency graph with the command _llvm-dg-dump -pta fs test.bc_ for the program bellow, the graph show data dependency edge between ```x.i = 3;``` and ```if(x.j)```, as well as ```arr[1] = 7;``` and ``` return arr[0];```, which is not right with flow sensitive.
Once the loop is removed by removing ```while(k--)```, the graph is fine.
```
struct tmp{
int i;
int j;
};

int main()
{
    struct tmp x = {0,0};
    int arr[]={0,0,0};
    int k=20;
    while(k--)
    {
        x.i = 3;
        x.j = 1;
        arr[1] = 7;
    }
    if(x.j)
        return arr[0];
    return 1;
}
```

**Comment by mchalupa** [comment]
Hi

yes, I know about this issue (I thought I filled an issue about it, but probably not as I can not find it). The problem is in GEP preprocessing, which was coded with a flow-insensitive analysis in mind.  It is a correct over-approximation even for flow-sensitive, but we loose some precision there. The problem is introduced in this function: https://github.com/mchalupa/dg/blob/master/src/analysis/PointsTo/PointerAnalysis.h#L90

The comment there is wrong, instead of
```C
// then every GEP will end up with UNKNOWN_OFFSET after some
```
it should read: 
```C
// then every GEP that is also stored to the same memory afterwards in the loop will end up with UNKNOWN_OFFSET after some
```

So a proper fix could be to fix `preprocessGEPs()` function. Easier fix would be making calling this function optionally.

**Comment by thierry-tct** [comment]
Hi,

Thanks much for you comment.
I now understand the problem, I will make some changes to bypass the optimization when sensitivity is enabled.

**Comment by mchalupa** [comment]
Hi,

thanks for the patch. I commented on two minor issues, but overall it looks good.

**Comment by thierry-tct** [comment]
Hi,

Sorry I didn't find the comment that you referred to.

P.S. I would also like to add the following feature on the ```llvm-dg-dump``` if that is okay: 
In the output _dot_ file, add an attribute on Node that shows the location of the llvm instruction on the original source code (if was compiled with -g option). so the dot file will look like this for a node:
```
NODE0Xxxxx [label=" store ...." labelURL="src/test.c:30:6" ...]
```
where the attribute ```labelURL``` will show the filename, line number and column number.
```labelURL``` will just be absent if the mapping to source is absent.
This can be useful for analysis where information on source code level is needed.

**Comment by mchalupa** [comment]
> Sorry I didn't find the comment that you referred to.

Sorry, I forgot to click on 'Submit review'. You should be able to find the comments now.

That sounds like a great feature! Feel free to go ahead (just please put it into a new pull-request). Also note that `llvm-slicer` can now dump the graph to dot too (`-dump-dg` switch)

**Comment by thierry-tct** [comment]
Alright, thanks.

I already submitted the changes on the pull request.

**Comment by mchalupa** [comment]
Thanks
