### ISSUE TITLE
Unhandled instruction

### ISSUE THREAD

**Issue by thierry-tct** [mchalupa/dg#125]
Hello, I have used dg on few project (make, grep, find) and I got the following issues:

- ```%8 = fptrunc double %7 to float, !dbg !2586```
_llvm-dg-dump: dg/src/llvm/analysis/PointsTo/PointerSubgraph.cpp:1454: dg::analysis::pta::PSNodesSeq dg::analysis::pta::LLVMPointerSubgraphBuilder::buildInstruction(const llvm::Instruction&): Assertion `0 && "Unhandled instruction"' failed._

-  ```double -1.000000e+00```
_ERROR: ^^^ global variable initializer not handled_

Could you please give me a hint on how I could change the code to enable the support for those instructions (highlighted).

P.S.: Furthermore, for some programs, dg run infinitely without printing any information. did you have such issue before?

Thanks much,

Thierry

**Comment by mchalupa** [comment]
For the `fptrunc`, the fix would be to add it here: https://github.com/mchalupa/dg/blob/master/src/llvm/analysis/PointsTo/PointerSubgraph.cpp#L1429

for the second case, I guess you need to dig into this code, but I do not know exactly what needs to be changed. I can look into it later: https://github.com/mchalupa/dg/blob/master/src/llvm/analysis/PointsTo/Globals.cpp#L45

> P.S.: Furthermore, for some programs, dg run infinitely without printing any information. did you have such issue before?

Yes, on some programs it is very expensive to compute the dependence graph, usually the reaching analysis takes the most time. Improvement for this would be to implement sparse analyses (however, there always will be some corner cases for which the analyses will run very long). 

A different "workaround" would be to add a timeout to reaching definitions analysis. It could then slice something even without having the whole information computed.

**Comment by thierry-tct** [comment]
Thanks much for the hints.

I will look at that.
