### ISSUE TITLE
Function called only through function pointer are not considered during analysis 

### ISSUE THREAD

**Issue by thierry-tct** [mchalupa/dg#133]
Function called only through function pointer are not considered during analysis and therfore not included in for example the dependency analysis.

EX: (code from ```od``` of ```coreutils```)
```
static void print_char(...){
      ...
}
main(){ ...
      print_function = (fmt == SIGNED_DECIMAL ? print_s_char : print_char);
       ...
      print_function (...)
}
```
Here the code of ```print_char``` is note analysed

**Comment by mchalupa** [comment]
Hi,

can you provide more information? Functions called only via function pointers should be considered during analyses. I tried with this example:

```C
  1 int x;
  2 
  3 void foo(int a) {
  4         x = 1;
  5 }
  6 
  7 void foo2(int a) {
  8         x = 2;
  9 }
 10 
 11 int main(void) {
 12         int a = 1;
 13         void (*f)(int) = (a == 1 ? foo : foo2);
 14         f(a);
 15         test_assert(x == 1);
 16         return 0;
 17 }
```

**Comment by thierry-tct** [comment]
Thanks for your reply, yes dg works fine for the  program that you posted. The one for coreutils ```od``` is a bit larger. I will try to go through and see why it does not generate dependency for that.

Thanks again

**Comment by thierry-tct** [comment]
I found the cause of the problem with the function pointer. The problem is that _realloc_ is not properly handled.
__See the example bellow:__ (`realloc` should behave like `malloc` when the pointer passed is _null_)
```c
#include <stdio.h>
#include <stdlib.h>

int x;

 void foo(int a) {
         x = 1;
 }

 void foo2(int a) {
         x = 2;
 }

 struct T {
      void (*f) (int c);
      int c;
 };

 int main(void) {
         int a = 1;
         struct T *pt = NULL;
         pt = (struct T*) realloc (pt, sizeof(struct T));
         //pt = (struct T*) malloc (sizeof(struct T));
         pt[0].f = (a == 1 ? foo : foo2);
         pt[0].f(a);
         //test_assert(x == 1);
         return 0;
}
```

1. This code when used as input to `llvm-dg-dump`, there is problem (__`WARNING: a call via a function pointer, but the points-to is empty`__ and therefore the function `foo` and `foo2` are not considered. 
But if the line with `malloc` if un-commented all work well, same with `calloc`.

2. When `realloc` is called after `malloc`, the problem is also present.

Thanks

**Comment by mchalupa** [comment]
can I turn this into a test-case?

**Comment by thierry-tct** [comment]
yes sure

**Comment by mchalupa** [comment]
Thanks!
