### ISSUE TITLE
Constant initialized array of struct with function pointer field: Pointer analysis fail

### ISSUE THREAD

**Issue by thierry-tct** [mchalupa/dg#135]
On the code bellow, `llvm-dg-dump` produce _`WARNING: a call via a function pointer, but the points-to is empty`_ and do not analyse the corresponding functions:
```c
int x;

 void foo(int a) {
         x = 1;
 }

 void foo2(int a) {
         x = 2;
 }

 struct T {
      void (*f) (int c);
      int c;
 };

 int main(void) {
         int a = 1;
         struct T tv[] = {{foo, 7}, {foo2, 4}};
         tv[0].f(a);
         //test_assert(x == 1);
         return  0;
}
```

**Comment by mchalupa** [comment]
Thanks for finding this issue! Can I use this piece of code as a test?

**Comment by thierry-tct** [comment]
You are welcome,thanks too for fixing it.

yes sure, feel free to use it as test.

**Comment by mchalupa** [comment]
Thanks!
