### ISSUE TITLE
Wrong pta result

### ISSUE THREAD

**Issue by hotpeperoncino** [mchalupa/dg#137]
Hi, thank you for your great work.
At location - MAYALIAS/NOALIAS operand "b" should hold PSNode (&d or non unitialize), but has no PSNode information.
command line option is -pta fs -pta-field-sensitive.
 
```
int main(){

    int **p,*q;
    int *a,*b,c,d, e,f;
    int *x;

    p = &a;
    if(e){
        if(c){
            q = &c;
        }
    }
    else{
        if(c)
            p = &b;
        q = &d;
    }
    if(f){
        *p = q;
    }

    MAYALIAS(b,&d);
    NOALIAS(b,&c);
}
```

**Comment by mchalupa** [comment]
Yes, it looks like a bug is FS analysis. Thanks for reporting it!

**Comment by hotpeperoncino** [comment]
Thank you for your effort, great.

2017-03-13 18:31 GMT+09:00 Marek Chalupa <notifications@github.com>:
