### ISSUE TITLE
catch testing framework?

### ISSUE THREAD

**Issue by tomsik68** [mchalupa/dg#144]
Hi, I see you want to improve the testing infrastructure, so I would like to propose porting unit tests to [catch framework](https://github.com/philsquared/Catch/blob/master/docs/tutorial.md). I thought I would discuss it before doing all the work, as there are quite a few tests that must be ported. 
In this issue, I try to convince you catch is a good framework and this project would benefit from using it :) 
Also, if you like catch, I would be willing to port all the unit tests to catch, too.

## Example
Catch supports 2 different styles of writing unit tests: traditional xUnit-style or Behavior Driven Development style. For the sake of demonstration, I ported `adt-test` to catch using both styles, so you can see both of them in action. You can [check it out in my fork](https://github.com/tomsik68/dg/blob/catch_tests/tests/adt-test.cpp). The tests are runnable, so you can feel free to pull and test it for yourself.

## Installation
Just add a single header file and that is it. Catch is a single-header framework, so no static/dynamic linking libraries are required and developer is not required to install special support libraries(which are required for googletest). 

## CTest compatibility
Catch is also compatible with CTest, so unit tests could be run along with slicing tests using `make test` as it is now. CTest, however, hides output of catch. That means, if you notice `adt-test` failing in CTest, you need to run the binary in order to see which assertion is failing. I am not sure how it works right now, but that is how it would work with catch.

### Sections
The most notable improvement against the current testing system is probably `SECTION`s. Sections save a lot of time writing tests that share the same code(e.g. initializing a data structure). 
Quick example of how sections work:
```cpp
TEST_CASE( "my_test" ) {
    INFO( "case" );
    SECTION( "test_section1" ) {
         INFO( "section1" );
    }
    SECTION( "test_section2" ) {
         INFO( "section2" );
    }
}
```
This prints(except some additional information):
```
case
section1
case
section2
```
This way, sections can be used to keep tests that share some code in single test case and run them completely separately.

On top of that, sections can be nested to simplify creation of more complex unit tests.

### 2 assertion macros
+ `REQUIRE` halts the test if the assertion fails
+ `CHECK` just reports failure and the test continues

### Error reporting

When catch reports an error, it reports precise context of the error along with the whole assertion that failed. Reporting the assertion elliminates the need to write error message for every single assertion. You can also find the error faster if the assertion is directly shown to you.
To demonstrate, I modified `adt-test` to fail:
```
$ ./adt-test
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
adt-test is a Catch v1.8.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
Scenario: LIFO
     Given: empty LIFO
      When: elements are pushed
      When: elements are popped
-------------------------------------------------------------------------------
/dg/tests/adt-test.cpp:27
...............................................................................

/dg/tests/adt-test.cpp:31: FAILED:
  REQUIRE( queue.pop() == 14 )
with expansion:
  13 == 14

===============================================================================
test cases:  3 |  2 passed | 1 failed
assertions: 19 | 18 passed | 1 failed

```

**Comment by mchalupa** [comment]
Hi,

sorry, kind of forgot about this issue, I'll check it ASAP.

Thanks,
Marek

**Comment by mchalupa** [comment]
Yes, this seems really nice :) Feel free to go ahead and add Catch when you have time.

Thanks!
Marek

**Comment by mchalupa** [comment]
Thanks for noticing.
