### ISSUE TITLE
Build fails with llvm 3.4.2

### ISSUE THREAD

**Issue by thierry-tct** [mchalupa/dg#145]
When building DG with llvm-3.4.2 I get the following error:
```Unknown CMake command "llvm_map_components_to_libnames".```

**Comment by dtzWill** [comment]
Hmm, I'm not seeing that problem.  Are you using a cmake build of LLVM 3.4?

Actually, judging by #147 and similar it seems you may have resolved this.  Can it be closed?

**Comment by thierry-tct** [comment]
@dtzWill yes I was using LLVM 3.4.3

**Comment by mchalupa** [comment]
I guess I can close this then. Reopen if needed ;)
