### ISSUE TITLE
slice cretiria

### ISSUE THREAD

**Issue by niuxu18** [mchalupa/dg#161]
is that possible to start slicer from given line in source code instead of function call site?

**Comment by mchalupa** [comment]
Hi,

no it is not, but you can insert a call to some dummy function on that line.

**Comment by happyhappiness** [comment]
thanks for your help and generous suggestion ^ ^

**Comment by mchalupa** [comment]
It should be possible now. When the program has debugging information, you can use line:variable as slicing criterion. There's still one restriction that the variable must be used on that line.
