### ISSUE TITLE
function returning struct looks losing the point-to info.

### ISSUE THREAD

**Issue by gadget114514** [mchalupa/dg#169]
Hi. I cannot get corrent point-to info on the following source.
the function returning struct looks losing the point-to info.
struct tag { int *p; };
int x;
struct tag foo() { struct tag n = {&x}; return n ; }
main() {
struct tag m = foo();
*m.p = 100;    // m.p becomes unknown; it should be point-to x;
}
// memory map does not have correct information;

**Comment by mchalupa** [comment]
Thanks for the report, I will look into that.

**Comment by mchalupa** [comment]
Could you post the commands that you used? When I use `ps-show` or `llvm-slicer -annotate pta -c ret` I get that `m.p` points to `x`:
```LLVM
; PTR: m + 0
%3 = getelementptr inbounds %struct.tag, %struct.tag* %m, i32 0, i32 0
; PTR: x + 0
%4 = load i32*, i32** %3, align 8
store i32 100, i32* %4, align 4
```

**Comment by mchalupa** [comment]
I guess the problem could be in the emitted LLVM. On my side, the LLVM did not pass the structure but just the pointer inside. If I add another element to that structure, then the code really needs to return a structure and then the PTA does not pass the information because `extractvalue` is used in the code (#94)

**Comment by mchalupa** [comment]
Just to fill in the reset of the info. The real problem is with returning the struct after all. So far, the analysis always assumed that `ret` can be used to return only a value (a pointer), so returning more pointers (aggregate, struct with pointers) does not work as excepted. I'll work on it.

**Comment by gadget114514** [comment]
thanks for your effort.

2018/01/05 午後5:55 "Marek Chalupa" <notifications@github.com>:

**Comment by mchalupa** [comment]
Just to confirm that I haven't forgotten this issue -- still working on it (I do not have much time for that, however)
