### ISSUE TITLE
"opt: CommandLine Error: Option 'disable-symbolication' registered more than once!" when building with dg library

### ISSUE THREAD

**Issue by gussmith23** [mchalupa/dg#182]
I have a simple LLVM pass, in which I eventually intend to use dg. Currently, though, the pass is simply empty. The CMake for the pass is:

```
find_library(LLVMdg_LIBRARY LLVMdg /home/mdl/hfs5022/usr/local/lib/)
target_link_libraries(DgTest ${LLVMdg_LIBRARY})
target_include_directories(DgTest PUBLIC /home/mdl/hfs5022/usr/local/include/llvm-dg)
```

The pass builds, but when I run `opt -load myPass.so`, I get the following error:

```
opt: CommandLine Error: Option 'disable-symbolication' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

Any clue what could be going on? My naive guess is that, at some point, some "registry" class (I would guess `OptionRegistry::registerOption`) is getting declared twice due to some portion of LLVM being linked in twice, once by my code and once because my code links with dg.

**Comment by gussmith23** [comment]
I can stop the error from occurring by simply commenting out the `target_link_libraries` line.

**Comment by gussmith23** [comment]
Perhaps I am misunderstanding how to use the library altogether!

**Comment by mchalupa** [comment]
> Any clue what could be going on? My naive guess is that, at some point, some "registry" class (I would guess OptionRegistry::registerOption) is getting declared twice due to some portion of LLVM being linked in twice, once by my code and once because my code links with dg.

Yes, that will be the problem. The CommandLine options are declared as `static` in a lot of cases, so if such an option is linked with your code and also by dg, then they collide, see https://github.com/mchalupa/dg/pull/124#issuecomment-264454888
We need to identify whether dg links to something that it does not need (or whether it leaks the symbols) or whether your pass links with something that it doesn't need: `PUBLIC`/`PRIVATE` linking flags need to be set properly.

**Comment by gussmith23** [comment]
Alright. I roughly understand what needs to be done, but I don't know what the next steps should be. Could you give me any guidance on how to debug this? 

Other than dg, my pass only links with LLVM. I do that using the following commands:
```
llvm_map_components_to_libnames(LLVM_LIBS core)
target_link_libraries(${PASS_NAME} PRIVATE ${LLVM_LIBS})
```

**Comment by gussmith23** [comment]
Something I'm confused by is that I'm getting this error when I try to use dg in the most basic of project setups. If I'm getting an error here, then I'm not sure how anyone uses dg as a library without hitting the same issue!

I made this gist to show my basic setup that is giving the error: https://gist.github.com/gussmith23/0f544d0ce8a5866c3ee8122ea10d23a4

**Comment by gussmith23** [comment]
By the way, if you know any quick hack for making this work even just temporarily, that would be really useful. I want to get started writing a pass that uses dg, but I'm blocked by this at the moment.

**Comment by mchalupa** [comment]
You are right that it is weird that we haven't been having more such problems when using dg. I think that I misunderstood how to link to LLVM libs. I just pushed a patch that changes linking with LLVM in dg. Then, what you need to do is to remove 

```cmake
llvm_map_components_to_libnames(LLVM_LIBS core)
target_link_libraries(${PASS_NAME} PRIVATE ${LLVM_LIBS})
```
from your `CMakeList.txt`. The LLVM libraries that are linked to opt should be used then.

Does this work for you?

**Comment by gussmith23** [comment]
That works! Great! I'm not sure I actually understand what's happening, though. I see the commit you just pushed, and I roughly understand the changes you've made, but the question I still have is: should I now avoid linking a target with both LLVMdg and LLVM libraries? Will linking with LLVMdg give me access to LLVM also?

**Comment by mchalupa** [comment]
I was thinking about the changes too and now I'm not sure they are entirely right, but at least it works now :) I need to go over linking LLVM in CMake a bit more. I think that you can link with both LLVMdg and LLVM now. Linking to LLVMdg will not give you access to LLVM, but it should not be a problem.

**Comment by mchalupa** [comment]
Closing this one, reopen if needed.
