### ISSUE TITLE
Node's data dependencies aren't populated after LLVMDependenceGraph is built

### ISSUE THREAD

**Issue by gussmith23** [mchalupa/dg#192]
I have a feeling this is NOT a bug, but rather, a gap in my understanding.

I'm trying to traverse through the data dependencies of a node using `dg::LLVMNode::data_begin()` and `dg::LLVMNode::rev_data_begin()`. The `LLVMNode` in question comes from an `LLVMDependenceGraph` which has been built from a module. However, I'm finding that every node has no data dependencies associated with it.

After looking through the code, it seems like the dependencies aren't calculated during `build()`, which isn't all that surprising. However, I'm not sure how to populate them. Is there some other function I should be running which will calculate the dependencies?

It looked like there might be code in DefUse.cpp to do this, but I wasn't sure if this is along the right path.

**Comment by mchalupa** [comment]
This could be considered a bug, or rather a feature request -- I should make the interface for building the graph more user-friendly. At this moment, after building the graph, you need to fill-in the edges using the def-use analysis, as you already noticed. See for example here: https://github.com/mchalupa/dg/blob/master/tools/llvm-slicer.cpp#L270

**Comment by mchalupa** [comment]
I added `LLVMDependenceGraphBuilder`, this should do the thing.
