### ISSUE TITLE
make on windows

### ISSUE THREAD

**Issue by Destinywck** [mchalupa/dg#196]
I tried to make the project on windows, but it failed.
environment:
    llvm: 3.8.0
    clang: 3.8.0
error:
    CMake Error at src/CMakeLists.txt:81(install):
    install Library TARGETS given no DESTINATION!
But it successed on linux(ubuntu), so I just want to know if this project can only be maked on linux, or how can I make it through on windows.
Thanks.

**Comment by mchalupa** [comment]
Hi,

I never tried on Windows and do not even plan to. But if you manage to build it on Windows, feel free to send PR ;)

**Comment by Destinywck** [comment]
Hi, 
Thank you for your time first, I tried to make the project to visual sln, the error above was solved. But there are so many errors in the sln project.
environment:
windows10;
visual studio 2015;
llvm: 3.8.0;
clang: 3.8.0;
Here is some errors in vs sln project:
[errors.txt](https://github.com/mchalupa/dg/files/1976554/errors.txt)

I used mingw to compile the llvm and dg, the llvm can make through but the dg also falsed.
I use gcc in both linux and windows as the compiler, It seems that there are some grammatical errors.
environment:
windows10;
gcc.exe (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 7.3.0;
cmake version 3.11.0-rc2;
mingw32-make version GNU Make 4.2.1 Built for i686-w64-mingw32;
Here is the build errors in mingw when build the dg:
[dg-mingw-errors.txt](https://github.com/mchalupa/dg/files/1977345/dg-mingw-errors.txt)

I'll really appreaciate it if you can offer some help.

**Comment by mchalupa** [comment]
It looks like the linking to LLM is not working properly. I would try to link to the LLVM libs in cmake.
