### ISSUE TITLE
Generate LLVMDependenceGraph for a function not reachable from main

### ISSUE THREAD

**Issue by anahitH** [mchalupa/dg#200]
Is there a way to make dg to generate LLVMDependenceGraph for a function that is not reachable from the main function?
I've tried to use LLVMDependenceGraph's build function which gets a function as an argument, however when slicing on the resulted graph I get an empty slice. 

Thanks!

**Comment by ManSoSec** [comment]
I made some changes for llvm-dg-dump and it seems it works correctly. You can get the slice by running -mark and set the entrypoint by -entrypoint. However, llvm-slicer is still buggy for me currently:

https://github.com/ManSoSec/dg
