### ISSUE TITLE
generate incorrect pdg when it comes to phi node(instruction)

### ISSUE THREAD

**Issue by Destinywck** [mchalupa/dg#201]
environment:
os: ubuntu 16.04.4 LTS x86_x64
llvm: 3.8.0
clang: 3.8.0

The clang and llvm work normally and the bitecode is normally generated, bug I got incorrect pdg when use llvmdg-show command.

My c source file content: fact.c

#include <assert.h>
#include <stdio.h>

long int fact(int x)
{
    long int r = x;
    while (--x >=2)
    {
	r *= x;
    }
    return r;
}

int foo(int a, int b)
{
    if(a > b)
        return a + b + 2;
    else
        return a * b * 17;
}

int main(void)
{
    int a, b, c = 7;
    while (scanf("%d", &a) > 0) {
	assert(a > 0);
	printf("fact: %lu\n", fact(a));
        foo(3, 4);
    }
    return 0;
}

Bug if I remove the function foo(); I will get correct result. So I just wonder if there is something wrong with PHI node(instruction). Or something wrong with my configuration.
Thamk you.

The make log of dg: 
[cmake-dg.log](https://github.com/mchalupa/dg/files/1990862/cmake-dg.log)

The error log of use of llvmdg-show: 
[llvmdg-show-error.log](https://github.com/mchalupa/dg/files/1990864/llvmdg-show-error.log)

**Comment by mchalupa** [comment]
Hi,

thanks for the report. I didn't understand what is the problem here. Is it that the PDG is constructed incorrectly or that llvmdg-show can not display the graph (the `lvmdg-show-error.log`)?

**Comment by Destinywck** [comment]
@mchalupa 
The PDG I got as bellow:
![11](https://user-images.githubusercontent.com/15710769/39964725-d0deeb20-56bd-11e8-808f-5359358898d3.png)

**Comment by mchalupa** [comment]
This still looks like that it is just incorrectly dumped. Could you try running `llvm-slicer -c __assert_fail -annotate slice` on your code? What is the output? (There will be also `-debug.ll` file generated, could you post it here?)

**Comment by Destinywck** [comment]
The slicer works normally.
And the result is here for your reference.
[fact.zip](https://github.com/mchalupa/dg/files/2003526/fact.zip)

**Comment by mchalupa** [comment]
This looks more like a bug in dot:
```
libpath/shortest.c:324: triangulation failed
libpath/shortest.c:192: source point not in any triangle
Error: in routesplines, Pshortestpath failed
...
Error: lost NODE0xae4050 NODE0xae4da0 edge

```

**Comment by Destinywck** [comment]
Does that mean I can just ignore it?

**Comment by Destinywck** [comment]
One thing to confirm: What you mean is the dg work well and .dot is right bug the xdot failed to display the figure. Is that right?

**Comment by mchalupa** [comment]
Yes, that is what I meant. Another possibility is that the .dot file is corrupted, but from what I know, I can not conclude that PDG is constructed incorrectly.

You can always use the C++ API (just build the PDG and then iterate over the nodes that you are interested in, see `llvm-slicer.cpp`)

**Comment by Destinywck** [comment]
I see. Pretty greatful for your help, thank you.
