### ISSUE TITLE
Is the control dependence graph equal to CFG?

### ISSUE THREAD

**Issue by 906072947** [mchalupa/dg#202]
I dump the dependence graph for  a program and also dump CFG for the same program ,find that the control dependence graph (blue line) is the same to the CFG .so how to explain it?

**Comment by mchalupa** [comment]
Can you show me the graphs? It may be a bug. CFG is not the same as CDG (however, dg dumps also CFG edges).

**Comment by mchalupa** [comment]
Closing this issue, re-open if needed.
