### ISSUE TITLE
Initialize NULLPTR, UNKNOWN_MEMORY, INVALIDATED.

### ISSUE THREAD

**Issue by hotpeperoncino** [mchalupa/dg#203]
At the end of pointer analysis , the special Object PSNODE NULLPTR, UNKNOWN_MEMORY, INVALIDATED still might have some values between analysis execution.
So the secondary trial of pointer analysis (with another PTA object) causes crash. because the special object still has pointer which the previous analysis used.
To fix, i inserted NULLPTR->setValue<MemoryObject>(0) at PointerAnalysis#createPTA.

**Comment by mchalupa** [comment]
Thanks for the report!

**Comment by mchalupa** [comment]
Hi,

is this issue still relevant? There have been some changes that should prevent this problem.

**Comment by mchalupa** [comment]
Closing this issue as done, re-open if needed.
