### ISSUE TITLE
How to remove the subgraph(BBlock) when dump the pdg into dot file.

### ISSUE THREAD

**Issue by Destinywck** [mchalupa/dg#204]
Hi, 
I want to remove the subgraph in the dumped result, and just keep the vertex and edge info. So I ask how to reshape the relation between subgraph into edges between vertexs so I can keep the correct CD and DD info. 
By the way, I saw a sclide of code in a file named "DG2Dot.h" line 183 as flow.
So is that mean I can just remove the subgraph sloppyly and I will not loss any info?

`void dumpSubgraphEnd(DependenceGraph<NodeT> *sub, bool with_nodes = true)
    {
        if (with_nodes) {
            // dump all nodes, to get it without BBlocks
            // (we may not have BBlocks or we just don't want
            // to print them
            for (auto I = sub->begin(), E = sub->end(); I != E; ++I) {
                dump_node(I->second, 2);
                dump_node_edges(I->second, 2);
            }

            if (dumpedGlobals.insert(sub->getGlobalNodes().get()).second) {
                for (auto& I : *sub->getGlobalNodes()) {
                    dump_node(I.second, 2, "GLOB");
                    dump_node_edges(I.second, 2);
                }
            }
        }

        out << "\t}\n";
    }`

Source code:
`#define _NO_CRT_STDIO_INLINE

#include <assert.h>

int main(void)
{
    int a = 7;

	if(a > 0)
		a = a - 1;
	else
		a = a + 1;
	
    return a;
}`
Your current llvm-dg-dump result: 
![simple](https://user-images.githubusercontent.com/15710769/40487718-9ace7f04-5f97-11e8-8275-dbec658b27dc.png)

What I want(seems something is wrong): 
![test](https://user-images.githubusercontent.com/15710769/40487727-a05b1018-5f97-11e8-972b-d36c896ff949.png)

I'll really appreciate your help, Thank you.

**Comment by mchalupa** [comment]
Yes, you can just dump the nodes and the edges between the nodes and ignore the rest. The problem will be with control dependencies, that are not in nodes but in basic blocks. So what you want to do is to take each basic block and dump a control dependence from the terminating instruction to all nodes in the blocks that are control dependent on this block.

**Comment by mchalupa** [comment]
Did you manage to achieve what you wanted?

**Comment by mchalupa** [comment]
Great! Let me close this issue then.
