### ISSUE TITLE
can i use std::unordered_set instead of std::set

### ISSUE THREAD

**Issue by hotpeperoncino** [mchalupa/dg#205]
I found that std::set manipulation occupies the time of execution.
if the replacement of std::set to unordered_set has no subeffect to result, i'd like to use unordered_set.
can i have your comment?

**Comment by mchalupa** [comment]
Sure, you can use whatever you want, it's open-source ;) Which std::set you want to replace exactly?

**Comment by hotpeperoncino** [comment]
sorry. i mistook. the both functions consume most time of analysis.

**Comment by hotpeperoncino** [comment]
I checked the following pages.
https://tessil.github.io/2016/08/29/benchmark-hopscotch-map.html
https://github.com/greg7mdp/sparsepp/blob/master/bench.md
http://www.clifford.at/blog/index.php?/archives/132-C++11-stdunordered_set-and-stdunordered_map-are-slower-than-a-naive-implementation.html

Also, I checked the result of profiler.
MemoryObject::addPointsTo and around consumes the most time of analysis. So the set of MemoryObject should be replaced to better one.

**Comment by mchalupa** [comment]
I'm glad that you came with this. I was currently working on very similar things. Check the pta-modernize branch (https://github.com/mchalupa/dg/tree/pta-modernize). There I have abstracted the points-to-set containers into a new object that can internally use either std::set or std::map/std::unordered_map. You can try that out.

**Comment by hotpeperoncino** [comment]
Thank you for your advice. i'll check pta-modernize version. i checked sparsepp and google::dense_hash_set to use it instead of std::unordered_set. according to author, sparsepp is slower than dense_hash_set but it is easy to use because of transparent compatibility to std::set.  i failed in trying google::dense_hash_set because of its incompatibility.

**Comment by hotpeperoncino** [comment]
I checked pta-modernize branch. it is great work having the compilation speed improved. this issue can be closed.
