### ISSUE TITLE
Assertion `!isRelevantInstruction(Inst)' fails

### ISSUE THREAD

**Issue by anahitH** [mchalupa/dg#206]
DG fails in  LLVMPointerSubgraphBuilder::buildBlockStructure when asserting on `isRelevantInstruction(Inst)`.
I've done some investigation and the instruction which is reported as non relevant is a load instruction for which` tryGetOperand(Inst.getOperand(0)` is returning UNKNOWN_MEMORY.

Attached is the bitcode to reproduce the issue.

[bitcnts.x.bc.zip](https://github.com/mchalupa/dg/files/2087066/bitcnts.x.bc.zip)

**Comment by mchalupa** [comment]
Thanks for the report, I'll check it.

**Comment by mchalupa** [comment]
Should be fixed in master, reopen if needed.
