### ISSUE TITLE
When analysing some source code, llvm-slicer goes wrong.

### ISSUE THREAD

**Issue by Deo-Ned** [mchalupa/dg#210]
LLVM-Slicer is truly a excellent analyser for codes in C. While I tried to analyze a source file in C++ and processed the command-"./llvm-slicer -c __assert_fail -annotate slicer 0_*coins.bc ", it displayed a error message-"Stack dump". Hence, I'd like to ask for help to solve this problem.

The C++ source codes are as follows:

`#include <iostream>

#include <string>

#include <cmath>

#include <vector>

using namespace std;

int coinCombinations(int coins[], int coinKinds, int sum, int special[], int n2)

{

    // 2-D array using vector: is equal to: dp[coinKinds+1][sum+1] = {0};

    vector<vector<int> > dp(coinKinds + 1);

    for (int i = 0; i <= coinKinds; ++i)

    {

        dp[i].resize(sum + 1);

    }

    for (int i = 0; i <= coinKinds; ++i)

    {

        for (int j = 0; j <= sum; ++j)

        {

            dp[i][j] = 0;

        }

    }

    for (int i = 0; i <= coinKinds; ++i)

    {

        dp[i][0] = 1;

    }

    for (int i = 1; i <= coinKinds; ++i)

    {

        for (int j = 1; j <= sum; ++j)

        {

            dp[i][j] = 0;

            for (int k = 0; k <= j / coins[i-1]; ++k)

            {

                dp[i][j] += dp[i-1][j - k * coins[i-1]];

            }

        }

    }

    long result=0;

    long flag= pow(2,n2);

    for(int i=0;i<flag;i++){

        int count1=0;

        for(int j=0;j<n2;j++){

            count1+=((i>>j)%2)*special[j];

            //cout<<count1<<endl;

        }

        if(count1>sum)

            break;

        result=result + dp[coinKinds][sum-count1];

        //cout<<result<<endl;

        if(result>10000000070000000)

            result%1000000007;

    }

    return result%1000000007;

 }

 int main()

 {

     int coins[100],special[100];

     int n1,n2,sum;

     cin>>n1>>n2>>sum;

     for(int i=0;i<n1;i++)

        cin>>coins[i];

     for(int i=0;i<n2;i++)

        cin>>special[i];

     cout << coinCombinations(coins, n1, sum, special, n2);

     return 0;

}`

Thank anyone for telling me any possible solution.

**Comment by mchalupa** [comment]
What is the error message? I assume the problem is that dg does not support C++ constructs.

**Comment by Deo-Ned** [comment]
Thx for your response. 

Well, I'd like to learn what your words mean in detail. Does it mean dg progrom is not good enough to support analysis of C++ files? Or dg can't analyze c++ codes.

And the error message is as follows:
`Stack dump:
0.	Program arguments: ./llvm-slicer -c __assert_fail -annotate slicer 15_j&&n2&&1.bc 
Aborted (core dumped)
llvm-dis "15_j&&n2&&1.sliced"
#0 0x4e29d2 llvm::sys::PrintStackTrace(_IO_FILE*) (/usr/local/bin/llvm-dis+0x4e29d2)
#1 0x4e0c91 SignalHandler(int) (/usr/local/bin/llvm-dis+0x4e0c91)
#2 0x7f2d6bff0390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
#3 0x42d13e llvm::AssemblyWriter::printModule(llvm::Module const*) (/usr/local/bin/llvm-dis+0x42d13e)
#4 0x42e1c6 llvm::Module::print(llvm::raw_ostream&, llvm::AssemblyAnnotationWriter*) const (/usr/local/bin/llvm-dis+0x42e1c6)
#5 0x404365 main (/usr/local/bin/llvm-dis+0x404365)
#6 0x7f2d6b393830 __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:325:0
#7 0x4060d9 _start (/usr/local/bin/llvm-dis+0x4060d9)
Stack dump:
0.	Program arguments: llvm-dis 15_j&&n2&&1.sliced 
Segmentation fault (core dumped)
`

**Comment by mchalupa** [comment]
DG could support C++, but it does not atm.

**Comment by mchalupa** [comment]
Could you attach the C++ file as an attachement? Thx.

**Comment by mchalupa** [comment]
Ping

**Comment by Deo-Ned** [comment]
Sorry for responding late. I guess I forgot the source code file.

Sorry again.
