### ISSUE TITLE
Can  I slice a program which has no main function ?

### ISSUE THREAD

**Issue by 906072947** [mchalupa/dg#211]
when I want to slicer a program without main function ,there goes something wrong and given a error message  "Need main function in module",so how can I  slice a program which has no main function ?

**Comment by mchalupa** [comment]
At this moment it is hard-coded that the entry function is the function called "main", so you need this function in the module (only functions that are reachable from this one are analyzed). You can hack this behavior in these places: 
https://github.com/mchalupa/dg/blob/master/src/llvm/LLVMDependenceGraph.cpp#L135
https://github.com/mchalupa/dg/blob/master/src/llvhttps://github.com/mchalupa/dg/blob/master/src/llvm/LLVMDependenceGraph.cpp#L135m/analysis/PointsTo/PointerSubgraph.cpp#L759
https://github.com/mchalupa/dg/blob/master/src/llvm/analysis/ReachingDefinitions/LLVMRDBuilderDense.cpp#L863

**Comment by mchalupa** [comment]
Should be solved now.
