### ISSUE TITLE
can't llvm-dis

### ISSUE THREAD

**Issue by joung96** [mchalupa/dg#235]
If I use the 'file' command to examine the .sliced file, it says LLVM IR bitcode. However, llvm-dis says this is an invalid value.

**Comment by jiwonjoung** [comment]
To add, I cannot execute the .sliced file by compiling it with clang either. Clang says 'File format not recognized'. I think the bigger question is how do I execute the slice?

**Comment by jiwonjoung** [comment]
I updated my llvm-dis version so llvm-dis is working. However, clang is still failing despite everything being version 8.0.0.

**Comment by mchalupa** [comment]
If you want to execute the slice, it should be possible to use `lli`.

**Comment by mchalupa** [comment]
If you want to compile the file using clang, you must rename the file from `.sliced` to `.bc`, because clang derives the formats from file suffix.

**Comment by jiwonjoung** [comment]
renaming the file worked -- thanks!

**Comment by joung96** [comment]
thanks
