### ISSUE TITLE
Make failed

### ISSUE THREAD

**Issue by DEILVER** [mchalupa/dg#237]
Hi,I tried to compile it,when I did `cmake .`,and it configured done.But when I  did `make -j4`,it failed with following information.
<pre>[ 95%] <font color="#4E9A06">Building CXX object tools/CMakeFiles/llvm-slicer.dir/llvm-slicer-opts.cpp.o</font>
In file included from <b>/home/rtco/dg/tools/llvm-slicer.h:24:0</b>,
                 from <b>/home/rtco/dg/tools/llvm-slicer-opts.cpp:9</b>:
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:</b> In member function ‘<b>void dg::LLVMSlicer::adjustBBlocksSucessors(dg::LLVMDependenceGraph*, uint32_t)</b>’:
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:300:25:</b> <font color="#EF2929"><b>error: </b></font>‘<b>TerminatorInst</b>’ in namespace ‘<b>llvm</b>’ does not name a type
             const llvm::<font color="#EF2929"><b>TerminatorInst</b></font> *tinst = llvmBB-&gt;getTerminator();
                         <font color="#EF2929"><b>^~~~~~~~~~~~~~</b></font>
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:372:37:</b> <font color="#EF2929"><b>error: </b></font>‘<b>tinst</b>’ was not declared in this scope
             for (uint8_t i = 0; i &lt; <font color="#EF2929"><b>tinst</b></font>-&gt;getNumSuccessors(); ++i) {
                                     <font color="#EF2929"><b>^~~~~</b></font>
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:372:37:</b> <font color="#34E2E2"><b>note: </b></font>suggested alternative: ‘<b>uint</b>’
             for (uint8_t i = 0; i &lt; <font color="#34E2E2"><b>tinst</b></font>-&gt;getNumSuccessors(); ++i) {
                                     <font color="#34E2E2"><b>^~~~~</b></font>
                                     <font color="#4E9A06">uint</font>
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:298:37:</b> <font color="#AD7FA8"><b>warning: </b></font>unused variable ‘<b>llvmBB</b>’ [<font color="#AD7FA8"><b>-Wunused-variable</b></font>]
             const llvm::BasicBlock *<font color="#AD7FA8"><b>llvmBB</b></font>
                                     <font color="#AD7FA8"><b>^~~~~~</b></font>
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:</b> In member function ‘<b>void dg::LLVMSlicer::reconnectBBlock(dg::LLVMBBlock*, llvm::BasicBlock*)</b>’:
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:498:9:</b> <font color="#EF2929"><b>error: </b></font>‘<b>TerminatorInst</b>’ was not declared in this scope
         <font color="#EF2929"><b>TerminatorInst</b></font> *tinst = llvmBB-&gt;getTerminator();
         <font color="#EF2929"><b>^~~~~~~~~~~~~~</b></font>
</pre>
<pre>In file included from <b>/home/rtco/dg/tools/llvm-slicer.h:24:0</b>,
                 from <b>/home/rtco/dg/tools/llvm-slicer.cpp:20</b>:
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:</b> In member function ‘<b>void dg::LLVMSlicer::adjustBBlocksSucessors(dg::LLVMDependenceGraph*, uint32_t)</b>’:
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:300:25:</b> <font color="#EF2929"><b>error: </b></font>‘<b>TerminatorInst</b>’ in namespace ‘<b>llvm</b>’ does not name a type
             const llvm::<font color="#EF2929"><b>TerminatorInst</b></font> *tinst = llvmBB-&gt;getTerminator();
                         <font color="#EF2929"><b>^~~~~~~~~~~~~~</b></font>
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:498:25:</b> <font color="#EF2929"><b>error: </b></font>‘<b>tinst</b>’ was not declared in this scope
         TerminatorInst *<font color="#EF2929"><b>tinst</b></font> = llvmBB-&gt;getTerminator();
                         <font color="#EF2929"><b>^~~~~</b></font>
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:372:37:</b> <font color="#EF2929"><b>error: </b></font>‘<b>tinst</b>’ was not declared in this scope
             for (uint8_t i = 0; i &lt; <font color="#EF2929"><b>tinst</b></font>-&gt;getNumSuccessors(); ++i) {
                                     <font color="#EF2929"><b>^~~~~</b></font>
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:498:25:</b> <font color="#34E2E2"><b>note: </b></font>suggested alternative: ‘<b>uint</b>’
         TerminatorInst *<font color="#34E2E2"><b>tinst</b></font> = llvmBB-&gt;getTerminator();
                         <font color="#34E2E2"><b>^~~~~</b></font>
                         <font color="#4E9A06">uint</font>
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:372:37:</b> <font color="#34E2E2"><b>note: </b></font>suggested alternative: ‘<b>uint</b>’
             for (uint8_t i = 0; i &lt; <font color="#34E2E2"><b>tinst</b></font>-&gt;getNumSuccessors(); ++i) {
                                     <font color="#34E2E2"><b>^~~~~</b></font>
                                     <font color="#4E9A06">uint</font>
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:298:37:</b> <font color="#AD7FA8"><b>warning: </b></font>unused variable ‘<b>llvmBB</b>’ [<font color="#AD7FA8"><b>-Wunused-variable</b></font>]
             const llvm::BasicBlock *<font color="#AD7FA8"><b>llvmBB</b></font>
                                     <font color="#AD7FA8"><b>^~~~~~</b></font>
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:</b> In member function ‘<b>void dg::LLVMSlicer::reconnectBBlock(dg::LLVMBBlock*, llvm::BasicBlock*)</b>’:
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:498:9:</b> <font color="#EF2929"><b>error: </b></font>‘<b>TerminatorInst</b>’ was not declared in this scope
         <font color="#EF2929"><b>TerminatorInst</b></font> *tinst = llvmBB-&gt;getTerminator();
         <font color="#EF2929"><b>^~~~~~~~~~~~~~</b></font>
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:498:25:</b> <font color="#EF2929"><b>error: </b></font>‘<b>tinst</b>’ was not declared in this scope
         TerminatorInst *<font color="#EF2929"><b>tinst</b></font> = llvmBB-&gt;getTerminator();
                         <font color="#EF2929"><b>^~~~~</b></font>
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:498:25:</b> <font color="#34E2E2"><b>note: </b></font>suggested alternative: ‘<b>uint</b>’
         TerminatorInst *<font color="#34E2E2"><b>tinst</b></font> = llvmBB-&gt;getTerminator();
                         <font color="#34E2E2"><b>^~~~~</b></font>
                         <font color="#4E9A06">uint</font>
[ 95%] Built target llvm-rd-dump
</pre>
<pre>In file included from <b>/home/rtco/dg/tools/llvm-dg-dump.cpp:45:0</b>:
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:</b> In member function ‘<b>void dg::LLVMSlicer::adjustBBlocksSucessors(dg::LLVMDependenceGraph*, uint32_t)</b>’:
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:300:25:</b> <font color="#EF2929"><b>error: </b></font>‘<b>TerminatorInst</b>’ in namespace ‘<b>llvm</b>’ does not name a type
             const llvm::<font color="#EF2929"><b>TerminatorInst</b></font> *tinst = llvmBB-&gt;getTerminator();
                         <font color="#EF2929"><b>^~~~~~~~~~~~~~</b></font>
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:372:37:</b> <font color="#EF2929"><b>error: </b></font>‘<b>tinst</b>’ was not declared in this scope
             for (uint8_t i = 0; i &lt; <font color="#EF2929"><b>tinst</b></font>-&gt;getNumSuccessors(); ++i) {
                                     <font color="#EF2929"><b>^~~~~</b></font>
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:372:37:</b> <font color="#34E2E2"><b>note: </b></font>suggested alternative: ‘<b>uint</b>’
             for (uint8_t i = 0; i &lt; <font color="#34E2E2"><b>tinst</b></font>-&gt;getNumSuccessors(); ++i) {
                                     <font color="#34E2E2"><b>^~~~~</b></font>
                                     <font color="#4E9A06">uint</font>
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:298:37:</b> <font color="#AD7FA8"><b>warning: </b></font>unused variable ‘<b>llvmBB</b>’ [<font color="#AD7FA8"><b>-Wunused-variable</b></font>]
             const llvm::BasicBlock *<font color="#AD7FA8"><b>llvmBB</b></font>
                                     <font color="#AD7FA8"><b>^~~~~~</b></font>
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:</b> In member function ‘<b>void dg::LLVMSlicer::reconnectBBlock(dg::LLVMBBlock*, llvm::BasicBlock*)</b>’:
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:498:9:</b> <font color="#EF2929"><b>error: </b></font>‘<b>TerminatorInst</b>’ was not declared in this scope
         <font color="#EF2929"><b>TerminatorInst</b></font> *tinst = llvmBB-&gt;getTerminator();
         <font color="#EF2929"><b>^~~~~~~~~~~~~~</b></font>
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:498:25:</b> <font color="#EF2929"><b>error: </b></font>‘<b>tinst</b>’ was not declared in this scope
         TerminatorInst *<font color="#EF2929"><b>tinst</b></font> = llvmBB-&gt;getTerminator();
                         <font color="#EF2929"><b>^~~~~</b></font>
<b>/home/rtco/dg/include/dg/llvm/LLVMSlicer.h:498:25:</b> <font color="#34E2E2"><b>note: </b></font>suggested alternative: ‘<b>uint</b>’
         TerminatorInst *<font color="#34E2E2"><b>tinst</b></font> = llvmBB-&gt;getTerminator();
                         <font color="#34E2E2"><b>^~~~~</b></font>
                         <font color="#4E9A06">uint</font>
tools/CMakeFiles/llvm-slicer.dir/build.make:86: recipe for target &apos;tools/CMakeFiles/llvm-slicer.dir/llvm-slicer-opts.cpp.o&apos; failed
make[2]: *** [tools/CMakeFiles/llvm-slicer.dir/llvm-slicer-opts.cpp.o] Error 1
</pre>
And the output of `cmake .`
<pre>root@rtco-OptiPlex-3050:/home/rtco/dg# cmake .
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type: 
-- Found LLVM 8.0.0svn
-- Using LLVMConfig.cmake in: /usr/local/lib/cmake/llvm
-- LLVM binaries: /usr/local/bin
-- Linker detection: GNU ld
-- LLVM include dir: /usr/local/include
-- LLVM libraries dir: /usr/local/lib
-- LLVM definitions: -D_GNU_SOURCE -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- Looking for headers in: /usr/local/include
-- Looking for libraries in: /usr/local/lib
-- Using compiler: /usr/bin/c++
-- Additional compilation flags:  -fno-rtti -std=c++11 -Wall -Wextra
-- CMAKE_INSTALL_LIBDIR: &quot;lib&quot;
-- CMAKE_INSTALL_INCLUDEDIR: &quot;include&quot;
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rtco/dg
root@rtco-OptiPlex-3050:/home/rtco/dg# 
</pre>

**Comment by jiwonjoung** [comment]
it should work out of the box with llvm 8 -- try remaking and reinstalling your llvm ?

**Comment by mchalupa** [comment]
Should be fixed in master.
