### ISSUE TITLE
Question about the use edge and data dependence edge.

### ISSUE THREAD

**Issue by Destinywck** [mchalupa/dg#244]
Recently I synchronized the commit from dg and encountered two questions, hope your help.

1. Can I take the use or user edge the same as data dependence edge?
    I do not need the use and user info in fact.
2. Why same nodes are not in a subgraph as before commit.
    Take a variable allocation as example, the allocation inst node is not in the subgraph 
    as the store inst node is.

Thank you!
@mchalupa

**Comment by mchalupa** [comment]
> Can I take the use or user edge the same as data dependence edge?

Yes, it is a data dependence and in the previous version of dg, it was included in data dependencies. In the current version of dg, data dependencies have been refined and divided into two: "direct" and "indirect". "direct" (use) dependency means that a node A uses node B as an operand. "indirect" (data) dependence means that node A reads values from memory that may have been generated by node B. 

> Why same nodes are not in a subgraph as before commit.
Take a variable allocation as example, the allocation inst node is not in the subgraph
as the store inst node is.

I'm not sure I understand the question. Which subgraph? Can you be more precise which nodes are missing?

**Comment by Destinywck** [comment]
> > Can I take the use or user edge the same as data dependence edge?
> 
> Yes, it is a data dependence and in the previous version of dg, it was included in data dependencies. In the current version of dg, data dependencies have been refined and divided into two: "direct" and "indirect". "direct" (use) dependency means that a node A uses node B as an operand. "indirect" (data) dependence means that node A reads values from memory that may have been generated by node B.
> 
> > Why same nodes are not in a subgraph as before commit.
> > Take a variable allocation as example, the allocation inst node is not in the subgraph
> > as the store inst node is.
> 
> I'm not sure I understand the question. Which subgraph? Can you be more precise which nodes are missing?

Thank you for your answer. And please negelct the second question, it's my fault.
