### ISSUE TITLE
RDA crash: function pointer never assigned, never called

### ISSUE THREAD

**Issue by tomsik68** [mchalupa/dg#245]
This bug was discovered while testing Symbiotic on this benchmark: https://github.com/sosy-lab/sv-benchmarks/blob/master/c/ddv-machzwd/ddv_machzwd_outl_true-unreach-call_false-valid-memtrack.i . The benchmark is part of MemSafety-LinkedLists category of SV-COMP.

How to reproduce: 
1. checkout & build Symbiotic version staticafi/symbiotic@5f6b411a .
2. start `symbiotic --no-optimize --dont-exit-on-error --32 --prp valid-deref ../sv-benchmarks/c/ddv-machzwd/ddv_machzwd_outl_true-unreach-call_false-valid-memtrack.i`

In the process of preparing program for verification, DG crashes during slicing. The crash occurs both with dense and semi-sparse RDA, as this is a functionality they share. Here's a link to full Symbiotic log: https://pastebin.com/UMDUXK5T . 
Maybe the points-to analysis failed to identify which function the pointer might point to? The benchmark contains globally-initialized structs containing functions. The functions are called by pointer during the program, so maybe the pointer analysis was unable to identify which functions.

Here's the disassembly of the file being sliced: https://pastebin.com/3yL8188X (raw file link: https://pastebin.com/raw/3yL8188X). The crash happens inside the `call_interrupt_handler` function in the program. Here's a short snippet(function starts at line 1760 of the disassembly):
```c
void call_interrupt_handler()
{
    unsigned short i;
    struct pt_regs regs;

    i = __VERIFIER_nondet_int();
    __VERIFIER_assume(i < 16);

    if (registered_irq[i].handler) {
      (* registered_irq[i].handler)((int)i, registered_irq[i].dev_id, &regs);
    }
}
```

The problem might be, that there is no irq registered throughout the whole program, so the points-to set for `registered_irq[i].handler` is empty, but that's just a guess. Also, `registered_irq[i].handler` remains `NULL`, so it's never called during runtime.

**Comment by mchalupa** [comment]
Looks fixed in the master branch, re-open if it is not the case.
