### ISSUE TITLE
problems about make -j4

### ISSUE THREAD

**Issue by yangnasd** [mchalupa/dg#268]
Hi, I tried to compile it, when I did cmake ., and it configured done. But when I did make -j4,it failed with following information. The output of cmake . is given in the picture.
![cmake](https://user-images.githubusercontent.com/37689872/55449909-05466900-5600-11e9-92ef-be248f129492.png)

![1](https://user-images.githubusercontent.com/37689872/55449798-99640080-55ff-11e9-87bf-66550e34a9e0.png)

**Comment by mchalupa** [comment]
If the commit did not fix the issue, please, re-open it.
