### ISSUE TITLE
Problems on forward slicing

### ISSUE THREAD

**Issue by yangnasd** [mchalupa/dg#271]
I appreciate your time. @mchalupa 
 I can get  forward slices and backward slices under your guidances.  I write an example called `simple.c` and run it.  The souce code is:
![cs orig](https://user-images.githubusercontent.com/37689872/56030185-d1c9b400-5d4e-11e9-8fc1-b7789baace3e.png)

But I have the following further questions.
Setting  slicing_criterion to `6:b`. To get its forward slice set, I executed `./llvm-slicer -forward -c 6:b ./sum/simple.bc`. The output said that `sliced away 32 from 34 nodes in DG`. I found that there are 34 nodes in `simple.dot` and  4 nodes in  `simple.forward-slicing.dot`.  4 instructions are existed in `simple.forward-slicing.ll`(Figure 1).  Does it means that there are 4 instructions in the forward slice set of `6:b`? If it is, I wonder that why  4 instructions in the forward slice set. I think that the forward slice set is consists of the instructions whose line number are 33, 35, 36, 37, 38, 39, 40, 41(in figure 2 `simple.original.ll` ) as these instructions are influenced by `6:b`. If the correct forward slice set is 33, 35, 36, 37, 38, 39, 40, 41,  where could I get them? I also generate `simple-debug.ll`.  The instruction on 34 represents variable `c` . I think  it is not in the forward slice set as it is not influenced by `6:b`.

Figure 1. simple.forward-slicing.ll
![simple forward-slicing ll](https://user-images.githubusercontent.com/37689872/56024238-316d9280-5d42-11e9-903b-6b589c1ae0ae.png)

Figure 2. simple.original.ll
![simple original ll](https://user-images.githubusercontent.com/37689872/56020445-c455ff00-5d39-11e9-8b9d-9a2771df7f1f.png)

File. `simple.forward-slicing.ll`, `simple.forward-slicing.ll`, `simple.original.ll` and `.dot` files
[file.zip](https://github.com/mchalupa/dg/files/3072473/file.zip)

Additionally, commands executed by us are:
1. `clang -g -c -emit-llvm ./sum/simple.c -o ./sum/simple.bc`
2. `./llvm-slicer -forward -c 6:b ./sum/simple.bc` (generated file is `simple.forward.sliced`)
3. `./llvm-dg-dump ./sum/simple.forward.sliced > ./sum/simple.forward-slicing.dot`
4. `llvm-dis ./sum/simple.forward.sliced`  (generated file is `simple.forward-slicing.ll`)
5. `llvm-dis ./sum/simple.bc`  (generated file is `simple.original.ll`)
6. `./llvm-dg-dump ./sum/simple.original.ll> ./sum/simple.original.dot`

**Comment by yangnasd** [comment]
Hi,
Do you have advice on  this problem?  If there is another way of acquiring forward-slices?  I want to try. 
Thank for your help  :)
@mchalupa

**Comment by mchalupa** [comment]
Hi @yangnasd, sorry for the delay, I've been quite busy lately. I'll try to check it tomorrow or on Monday.
Cheers,
Marek

**Comment by yangnasd** [comment]
I appreciate your kind help. You can check it  at your convenience. Thank you again. :)

**Comment by mchalupa** [comment]
Should be fixed in master now. Can you check?

Cheers,
Marek

**Comment by yangnasd** [comment]
It works now. Thank you. :)

**Comment by mchalupa** [comment]
Great!
