### ISSUE TITLE
Can dg get the dependence graph of the whole progam, not a single file

### ISSUE THREAD

**Issue by lxy0816** [mchalupa/dg#273]
`./llvm-dg-dump bitecode.bc > file.dot` can get the dependence graph of bitcode.c  ,but if there is a program which consists of main.c, a.c, b.c, d.c, e.c ad so on. Can dg get the dependence graph of the whole program. If can, how should I do?

**Comment by mchalupa** [comment]
You can you `llvm-link` to link the bitcodes into a single file (it is actually written in the README ;). Or check projects like `wllvm`.

**Comment by mchalupa** [comment]
Closing this question since it is not related to dg, but rather to LLVM.
