### ISSUE TITLE
dg hangs forever on simple code

### ISSUE THREAD

**Issue by ivanpostolski** [mchalupa/dg#279]
I've compiled dg with llvm 3.6.0
Then tried to run it with the following source code

```
#include <stdio.h>      /* printf, scanf, NULL */
#include <stdlib.h> 
#include <string.h>

int len(char* input){
	return 6;
}

int f(int value){
	if (value > 315){
		int j = len("value > 315\n");
		return j;
	}

	int nvalue = value * 2;

	return nvalue;
}

int main(int argc, char **argv) {
   int input = atoi(argv[1]);
   int x;
   if (input > 100){
   	  x = f(input);
   } else {
   	  x = len("another input string");
   }

   return x;
}
```

compiled the source code with clang-3.6

`clang-3.6 -flto -g -c test.c -o tmp/test.bc`

Then tried to run 

`dg/tools/llvm-dg-dump tmp/test.bc > test.dot`

I killed when the test.dot file reached 3.5 GB

**Comment by mchalupa** [comment]
What is the version of dg that you use? It works for me, I'm getting:

```
CPU time of pointer analysis: 5.435000e-03 s
CPU time of reaching definitions analysis: 4.964000e-03 s
CPU time of control dependence analysis: 3.230000e-04 s
```

However, I haven't tried it with LLVM 3.6...

**Comment by ivanpostolski** [comment]
I'm using master. It happens on LLVM 3.6, but works on 6.0.0

**Comment by mchalupa** [comment]
Thanks, I'll try on 3.6 then.

**Comment by mchalupa** [comment]
Sorry for the delay. Could you check that the fix works? Thanks.
