### ISSUE TITLE
About backward and forward slicing

### ISSUE THREAD

**Issue by Tigerly** [mchalupa/dg#284]
Hello,

I'm a beginner of program slicing and DG tool. I found that the llvm-slicer tool has an option "-forward". So, I guess the llvm-slicer will do "backward slicing" as default, and do "forward slicing" when having the option "-forward". Is my understanding correct?

Thanks in advance!

**Comment by mchalupa** [comment]
Hi,

yes, you're correct. Although, the forward slicing is rather experimental and I am not sure how much it works right now (haven't touched the code for some time). Of course, if you find any bug there, please file an issue so that I can fix it.

**Comment by mchalupa** [comment]
(I'm closing the issue since the question was answered. Re-open it if needed.)
