### ISSUE TITLE
Unhandled instruction "atomicrmw"

### ISSUE THREAD

**Issue by Weissle** [mchalupa/dg#287]
clang++ and llvm versions are both 7.0.0 .  

weiss@ubuntu:~/Downloads/temp2$ ./llvm-dg-dump openssl.ll
  %20 = atomicrmw add i32* %19, i32 1 seq_cst, !dbg !136166
llvm-dg-dump: /home/weiss/Downloads/dg/lib/llvm/analysis/PointsTo/PointerSubgraph.cpp:501: dg::analysis::pta::PSNodesSeq dg::analysis::pta::LLVMPointerSubgraphBuilder::buildInstruction(const llvm::Instruction&): Assertion `0 && "Unhandled instruction"' failed.
Aborted (core dumped)

Is there any way to fix it?

Thanks

**Comment by Weissle** [comment]
I tried version 3.8.0 and this issue exists.

**Comment by mchalupa** [comment]
Hi,
The way to fix it is to implement the support for this instruction. It should not be that hard, but I will not have time to do that in the near future. Meanwhile, you can use loweratomic pass to transform atomic instructions to non-atomic once.
