### ISSUE TITLE
Bug Report - dg::analysis::rd::RD Node* dg::analysis::rd::LLVM IRBuilder::create UndefinedCall(const llvm::CallInst*): Assertion `(nodes_map.find(CInst) == nodes_map.end()) && "Adding node we already have"' failed.

### ISSUE THREAD

**Issue by Marvinmw** [mchalupa/dg#309]
Bug Report - llvm-dg-dump
dg::analysis::rd::RD Node* dg::analysis::rd::LLVM IRBuilder::create UndefinedCall(const llvm::CallInst*): Assertion `(nodes_map.find(CInst) == nodes_map.end()) && "Adding node we already have"' failed.

**Comment by mchalupa** [comment]
Do you have more information (how to reproduce, etc.?)

**Comment by Marvinmw** [comment]
hi, I use Coreutils and try dumping dot file for cp program.

**Comment by mchalupa** [comment]
hmm, ok. A bit more information? Could you e.g., provide the file on which this assertion is triggered and the command that you use?

**Comment by mchalupa** [comment]
Ping.

**Comment by Marvinmw** [comment]
Hi, Sorry I responded you too lately. I am trying my best to one recent deadline. I use the same setting in llvm-dmup. After the deadline, I give you the details. Much thanks.

**Comment by mchalupa** [comment]
There have been many changes to dg and this bug is not probably present anymore (DDA was rewritten). Re-open if this is not true ;)
