### ISSUE TITLE
Test fail from Test #15

### ISSUE THREAD

**Issue by covera** [mchalupa/dg#310]
Hi,

dg works fine to generate dependence graph, but fails when doing slicing.
The result of "make check" shows the test case failed from Test15
<img width="347" alt="截圖 2020-03-03 下午8 25 30" src="https://user-images.githubusercontent.com/11835713/75775798-b663ff00-5d8d-11ea-9dc8-57a8a01db06e.png">
<img width="416" alt="截圖 2020-03-03 下午8 25 21" src="https://user-images.githubusercontent.com/11835713/75775803-bb28b300-5d8d-11ea-866f-08aba64c3dbc.png">

I also tried generate CFG and slice my code. The sliced code isn't compilable and executable, too.
The version of LLVM I'm using is 6.0.0, detailed as below:
<img width="837" alt="截圖 2020-03-03 下午8 24 29" src="https://user-images.githubusercontent.com/11835713/75776057-2d00fc80-5d8e-11ea-9db7-ed27273a22fb.png">

I would like to know what the possible reason of failing slicing? Thanks!

**Comment by mchalupa** [comment]
> I also tried generate CFG and slice my code. The sliced code isn't compilable and executable, too.

What are the commands that you use and their output?

Also, what is the output of some of the failed tests? Try running e.g.,:

```shell
bash -x tests/slicing-test1.sh
```

**Comment by mchalupa** [comment]
I guess that there will be a problem with LLVM binaries. The tests try to use `llvm-link`, `clang`, and `lli`. If, on your system, the binaries are called differently (e.g., `clang-6`), then the test fails.

**Comment by covera** [comment]
> I guess that there will be a problem with LLVM binaries. The tests try to use `llvm-link`, `clang`, and `lli`. If, on your system, the binaries are called differently (e.g., `clang-6`), then the test fails.

Hi,

Thanks for swift reply. I do have multiple versions of clang and llvm.
After I force it executes with version 6.0 with command(apply to clang++, llvm, lli, llvm-link as well)
`update-alternatives --install /usr/bin/clang clang /usr/bin/clang-6.0 1000`

Almost all test passed:
<img width="360" alt="截圖 2020-03-04 上午10 33 07" src="https://user-images.githubusercontent.com/11835713/75839683-552b4280-5e04-11ea-9580-41601bb5dea7.png">

However, there are still 4 tests failed, the output of running`bash -x tests/slicing-phi1.sh
` shows
<img width="822" alt="截圖 2020-03-04 上午10 34 30" src="https://user-images.githubusercontent.com/11835713/75840014-3a0d0280-5e05-11ea-952f-b7fad5924090.png">


I think the solution could be similar to solutions above (just alternative certain binaries)
While using this command is not a proper solution.
What's the suggest way for me to link to desired binaries?

p.s.
When make the project dg, I've used the configuration:
`cmake -DLLVM_SRC_PATH=/usr/lib/llvm-6.0 -DLLVM_BUILD_PATH=/usr/lib/llvm-6.0/build -DLLVM_DIR=/usr/lib/llvm-6.0/lib/cmake/llvm/ .`
But I still need to alternative clang, llvm, ...,etc. manually.

**Comment by mchalupa** [comment]
> What's the suggest way for me to link to desired binaries?

The problem is not in linking to LLVM, but with calling the right binaries. `dg` is compiled with LLVM 6, so you must generate the LLVM bitcode that you pass to it by binaries that also have the LLVM version 6.
So you must properly setup the `PATH` environment variable, possibly with creating links to the right binaries if the binaries do not have the standard names. E.g.,

```shell
ln -s `which clang-6` clang
ln -s `which opt-6` opt
# etc.
export PATH=$(pwd)
```

**Comment by covera** [comment]
> So you must properly setup the `PATH` environment variable, possibly with creating links to the right binaries if the binaries do not have the standard names. E.g.,
> 
> ```shell
> ln -s `which clang-6` clang
> ln -s `which opt-6` opt
> # etc.
> export PATH=$(pwd)
> ```
Hi,

I've specified the PATH but it doesn't work for me. Though setting PATH environment seems the correct way, I turned to alternative command to fix the testing problem temporarily:

`sudo update-alternatives --install /usr/bin/opt opt /usr/bin/opt-6.0 1000`

After entering command above, all tests passed! I think this issue could be closed.
Thanks a lot for your help ;)
