### ISSUE TITLE
question about a simple example

### ISSUE THREAD

**Issue by ChaosLee03** [mchalupa/dg#318]
I have tested a simple example for DG.
The code as follow
`#include<iostream>
#include <assert.h>
using namespace std;

int main()
{
	int i,j;
	i = 1;      
	j = 2;      
	int k;     
	if ( i > j)
		k = i;
	else
		k = j;
	assert(k > 1);
	return 1;
}`

and the sliced code is
6: {
8:      i = 1;
9:      j = 2;
11:     if ( i > j)
12:             k = i;
14:             k = j;
15:     assert(k > 1);
17: }

My question is why line 13, the statement of 'else' was sliced?

**Comment by mchalupa** [comment]
I guess you used the `llvm-to-source` tool. This tool only takes the bitcode and prints lines of C code that have a corresponding instruction in the bitcode (as determined by metadata). The 'else' statement  does not have its own instruction. Both lines 'if (i > j)` and `else` are covered by one `br` instruction in the bitcode and this instruction has the line `if (i > j)` assigned. Therefore, only this line is printed. You may try running `llvm-to-source` on the original, unsliced program. There the else line is missing too. So to answer your question: it was not sliced away, it was never explicitly in the bitcode.

**Comment by mchalupa** [comment]
btw. `llvm-to-source` tries to do some heuristics based on counting parentheses. If you wrap the code in the if-else construct explicitly to {}, then the else is shown.

**Comment by ChaosLee03** [comment]
Thanks a lot, I amtrying.
