### ISSUE TITLE
Fix GCC 4/5 builds

### ISSUE THREAD

**Issue by lzaoral** [mchalupa/dg#319]
Hi,
this patch should fix CI in the development branches. The thing is that `return {a,b}` with `std::tuple` was added to C++11 much later by a defect report (suppoted as of `libstdc++` 6). Changing `std::tuple` to `std::pair` makes the code compile with older releases of the GNU standard C++ library. Thus, making `dg` compatible with all C++11 compliant releases of GCC.

```diff
diff --git a/include/dg/llvm/PointerAnalysis/LLVMPointsToSet.h b/include/dg/llvm/PointerAnalysis/LLVMPointsToSet.h
index 888d0e6..6534202 100644
--- a/include/dg/llvm/PointerAnalysis/LLVMPointsToSet.h
+++ b/include/dg/llvm/PointerAnalysis/LLVMPointsToSet.h
@@ -114,7 +114,7 @@ class LLVMMemoryRegionSet {
     // (llvm::Value corresponding to the allocation)
     MappingT _regions;

-    std::tuple<Offset, Offset> _extend(const OffsetPair interval,
+    std::pair<Offset, Offset> _extend(const OffsetPair interval,
                        const Offset off, const Offset len) {
         assert(interval.overlaps(off, len));
         assert(!off.isUnknown());
```

I can make a PR, but I'm not sure to which development branch should I merge to.

**Comment by mchalupa** [comment]
You can create a PR against the master branch and I will rebase the developement branches on that. Thanks!

**Comment by lzaoral** [comment]
The PR is ready at #320. Unfortunately, the given header is not present in master, so I chose a branch that seems to be the closest to the what is used by symbiotic at the moment.

**Comment by mchalupa** [comment]
Hmm, do you have up to date master branch?
I can see it there: https://github.com/mchalupa/dg/blob/master/include/dg/llvm/PointerAnalysis/LLVMPointsToSet.h

**Comment by lzaoral** [comment]
Yeah sorry, I forgot to fetch the latest changes... I will fix the PR.

**Comment by lzaoral** [comment]
The PR should be ready now.

**Comment by mchalupa** [comment]
Thanks.
