### ISSUE TITLE
What is the form of slicing criterion in the command？

### ISSUE THREAD

**Issue by zzylol** [mchalupa/dg#324]
Hi, thanks for this nice tool! I am new here, and I want to ask what is the form of slicing criterion in the command? Is there any manual can help?

**Comment by mchalupa** [comment]
Try checking the README, namely this part:
> The slicing_criterion is a call-site of some function or ret to slice with respect to the return value of the main function. Alternatively, if the program was compiled with -g option, you can also use line:variable as slicing criterion. Slicer then will try finding a use of the variable on the provided line and marks this use as slicing criterion (if found). If no line is provided (e.g. :x), then the variable is considered to be global variable. You can provide a comma-separated list of slicing criterions, e.g.: -c crit1,crit2,crit3.
There's also an example in the README, but I'll give you another one here. Consider this program:
```C
1. int main() {
2.   int a = 8, b = input();
3.   while (a > b) {
4.     ++b;
5.   }
6.   check(a == b);
7.   check2();
8.   print(a)
}
```

You can say that the slicing criteria are calls to function `check` (`-c check`), therefore the slicer will detect the calls to `check` and slice the code w.r.t. these calls (including their arguments, as the arguments are used by the calls). Therefore, the slice w.r.t. `-c check` would correspond to:

```C
1. int main() {
2.   int a = 8, b = input();
3.   while (a > b) {
4.     ++b;
5.   }
6.   check(a == b);
}
```

The same way you can say that the slicing criteria are calls to `check2`, in which case the slice would be just:
```C
7. check2();
```
as `check2` does not use any variables and therefore has no dependencies (well, this is not true with non-termination sensitive control dependence).

Alternatively, if you compile the program to LLVM with debugging information (`-g` option), you can specify a line and variable that should be used as slicing criterion. In our example, if you use `-c 8:a`,
then the program is sliced w.r.t accesses to variable `a` on line 8, so the slice would be:
```C
1. int main() {
2.   int a = 8;
8.  // read of a will stay in LLVM here
}
```
Here is a restriction that the specified variable must be used at the given line. Just to fill in the details, a slicing criterion is always a node of a dependence graph. If you dump the dependence graph of the program (`-dump-dg`), then you can see what nodes are there and therefore what can be a slicing criterion. Alternatively, nodes in dep. graph correspond to instructions, so a slicing criterion is always an instruction in LLVM (check `-annotate slice` option, which generates `-debug.ll` file with information about sliced instructions; slicing criteria are marked in the file too).

Is this what you were asking for?

**Comment by zzylol** [comment]
That is what I was asking for. Thank you for your reply!

**Comment by mchalupa** [comment]
This issue has been reflected in the doc, so I am closing it (reopen if needed).

**Comment by wliuxingxiangyu** [comment]
@mchalupa 
Hi, thanks for this nice tool! 
When I apply two slicing criterions, the criterions format is "-c crit1,crit2", crit1="line1:var",  crit1="line2:var"
then[ getSlicingCriteriaValues() in llvm-slicer-crit.cpp](https://github.com/mchalupa/dg/blob/ce1b0724f3fd71cff6c0c47b81cfe8918c456c32/tools/llvm-slicer-crit.cpp#L1124) return {}. I wonder it is right.



I search all the code to find how to apply more than one slicing criterions.  Could you please give some examples about the scenery.

**Comment by mchalupa** [comment]
@wliuxingxiangyu, It looks like a bug. I get this error message: `Unsupported criteria: 7:s,11:e` on my testing program, but if I try each of the criteria separately, it works.

**Comment by mchalupa** [comment]
@wliuxingxiangyu Please try the fix in the commit above.
