### ISSUE TITLE
Support dynamic linking to LLVM

### ISSUE THREAD

**Issue by mchalupa** [mchalupa/dg#330]
Some systems does not contain the static libraries. See #327.

**Comment by lzaoral** [comment]
I have tried building `dg` in my fork https://github.com/lzaoral/dg/commit/4983408ef06fbcc9d8ca10b1522a084d060e0ef7 with dynamic libraries only. I had to rename the `threads` option as it conflicted with an [built-in option][1] of the same name but apart from that everything seems to work just fine. As all major distributions ship dynamic LLVM by default, it may be easier to just drop static linking to LLVM completely than to support both options.

[1]: https://github.com/llvm/llvm-project/blob/d7fad626e9a5e3dabdc56942d8965b9878326807/llvm/lib/LTO/ThinLTOCodeGenerator.cpp#L86

**Comment by mchalupa** [comment]
Thanks, I'll check it out.
