### ISSUE TITLE
Problem when build DG with LLVM.10

### ISSUE THREAD

**Issue by ChaosLee03** [mchalupa/dg#333]
Can DG support LLVM.10, I have got some problem when $make , such as this:
 error: no type named 'CompositeType' in namespace 'llvm'; did you mean 'DICompositeType'?
    llvm::CompositeType *type

**Comment by mchalupa** [comment]
Can you provide more details? I am using LLVM 10 and it works fine.

**Comment by ChaosLee03** [comment]
> Can you provide more details? I am using LLVM 10 and it works fine.

Thx, I have fix it by reinstall my LLVM. 
But there is another problem: when I use `clang -g` , the llvm-slicer report error?

**Comment by ChaosLee03** [comment]
The detail information as such:
test.c is the case:
`1. int main() {
2.   int a = 8, b = input();
3.   while (a > b) {
4.     ++b;
5.   }
6.   check(a == b);
7.   check2();
8.   print(a)
}`

and the report is:
root@DESKTOP-DVHH492:/mnt/d/dg/tools# clang -c -g -emit-llvm test.c -o test.bc
test.c:2:18: warning: implicit declaration of function 'input' is invalid in C99 [-Wimplicit-function-declaration]
  int a = 8, b = input();
                 ^
test.c:6:3: warning: implicit declaration of function 'check' is invalid in C99 [-Wimplicit-function-declaration]
  check(a == b);
  ^
test.c:7:3: warning: implicit declaration of function 'check2' is invalid in C99 [-Wimplicit-function-declaration]
  check2();
  ^
test.c:8:3: warning: implicit declaration of function 'print' is invalid in C99 [-Wimplicit-function-declaration]
  print(a);
  ^
4 warnings generated.
root@DESKTOP-DVHH492:/mnt/d/dg/tools# ./llvm-slicer -c 8:a test.bc
llvm-slicer: test.bc: error: Invalid record
Failed parsing 'test.bc' file:

**Comment by ChaosLee03** [comment]
The detail information as such:
test.c is the case:
`int main() {
  int a = 8, b = input();
  while (a > b) {
    ++b;
  }
  check(a == b);
  check2();
  print(a);
}`
and the report is:
root@DESKTOP-DVHH492:/mnt/d/dg/tools# clang -c -g -emit-llvm test.c -o test.bc
test.c:2:18: warning: implicit declaration of function 'input' is invalid in C99 [-Wimplicit-function-declaration]
int a = 8, b = input();
^
test.c:6:3: warning: implicit declaration of function 'check' is invalid in C99 [-Wimplicit-function-declaration]
check(a == b);
^
test.c:7:3: warning: implicit declaration of function 'check2' is invalid in C99 [-Wimplicit-function-declaration]
check2();
^
test.c:8:3: warning: implicit declaration of function 'print' is invalid in C99 [-Wimplicit-function-declaration]
print(a);
^
4 warnings generated.
root@DESKTOP-DVHH492:/mnt/d/dg/tools# ./llvm-slicer -c 8:a test.bc
llvm-slicer: test.bc: error: Invalid record
Failed parsing 'test.bc' file:

**Comment by ChaosLee03** [comment]
> Can you provide more details? I am using LLVM 10 and it works fine.

Thx, I fix it by reinstall my LLVM.
There is another question, when I sliced the code by global variables,  Can we get all the dependencies of this global variable？  
For example, I have de program as follow:
`int g;
int main()
{
	int i,j,k;
	i = 1;
	j = 2;
	k = 3;
	g = k;
	return 1;
}`
I want to get the slicer as such:
`int g;
int main()
{
	int i,j,k;
	
	k = 3;
	g = k;
	return 1;
}`
But when I using ./llvm-slicer -c :g, I got nothing, all the code are sliced.

**Comment by ChaosLee03** [comment]
> Can you provide more details? I am using LLVM 10 and it works fine.

Thx , I have fix it by reinstall LLVM.
There is another problem. I want to slice a program by using global variables.
My source code as follow:
`
int g;
int main()
{
	int i,j,k;
	i = 1;
	j = 2;
	k = 3;
	g = k;
	return 1;
}
`
I thought I can get the slicer as such:
`
int g;
int main()
{
	int i,j,k;

	
	k = 3;
	g = k;
	return 1;
}
`
But the result of slicer(./llvm-slicer -c  :g test.bc)  is nothing, all the code are sliced. So how can I get all the dependencies of this global variable.

**Comment by ChaosLee03** [comment]
> Can you provide more details? I am using LLVM 10 and it works fine.

Thx , I have fix it by reinstall LLVM.
There is another problem. I want to slice a program by using global variables.
My source code as follow:
int g; 
int main()
 { 
int i,j,k; 
i = 1;
 j = 2;
 k = 3;
 g = k; 
return 1;
 }
I thought I can get the slicer as such:

int g;
int main()
{
int i,j,k;

k = 3;
g = k;
return 1;
}


But the result of slicer(./llvm-slicer -c :g test.bc) is nothing, all the code are sliced. So how can I get all the dependencies of this global variable.

**Comment by mchalupa** [comment]
`-c :g` should be matched with the definition of the global `g`, and this definition is not dependent on anything. To get what you want, you must specify the line: `-c 8:g`. Or you can insert a call of a dummy function at the place where you need that uses `g` (i.e., `dummy(g)` at line 8) and then use `-c dummy`. That would remove the line `g=k` though.

**Comment by ChaosLee03** [comment]
> `-c :g` should be matched with the definition of the global `g`, and this definition is not dependent on anything. To get what you want, you must specify the line: `-c 8:g`. Or you can insert a call of a dummy function at the place where you need that uses `g` (i.e., `dummy(g)` at line 8) and then use `-c dummy`. That would remove the line `g=k` though.

Thank you for your reply, but I'm still confused.As far as I know, global variables have their own names in IR， so why g=k would be remove?  
I imagined a scenario where a program is very large. We don't know where this variable was last used, but we want to slice the variable，so I must find the last use of it?

**Comment by mchalupa** [comment]
Global variables have their names, but the slicing criterion is a particular use or several particular uses of the variable. So yes, if you want to slice w.r.t the last use, you must find the last use.

**Comment by mchalupa** [comment]
I'm closing this issue as the problem with the building was resolved. Feel free to start a new issue about the names and slicing criteria if needed.
