### ISSUE TITLE
Does value-relations analysis mean finding what variables affect a specific part of code?

### ISSUE THREAD

**Issue by zzylol** [mchalupa/dg#337]
Hi! I need to do something like finding what variables affect a specific part of code intraprocedurally. Does value-relations analysis part mean that? 
Thank you!

**Comment by mchalupa** [comment]
Hi,

no, the closest notion to what you describe is "forward slicing" (which is based on "value-flow analysis" or "dependence analysis").

**Comment by mchalupa** [comment]
I'm closing this question as it is not actually an issue, we can, of course, continue the discussion in this thread after closing (or re-open it if you like)
