### ISSUE TITLE
Error when building with SVF support

### ISSUE THREAD

**Issue by vwvw** [mchalupa/dg#338]
When I tried to build dg with SVF support I got multiple errors.

Some where due to this [commit](https://github.com/SVF-tools/SVF/commit/04ea1957c1262ed45658e17cd501eaef801a34e0) while other are cause by a [change](https://github.com/SVF-tools/SVF/commit/2b372677f378c0c424a0f8d0a0625fbb5d4d4e76) in the namespace used by SVF.

I have my fixes [here](https://github.com/vwvw/dg/tree/fixes) but still get an error:

```bash
make[2]: *** [tools/CMakeFiles/llvm-slicer.dir/build.make:132: tools/llvm-slicer] Error 1
make[1]: *** [CMakeFiles/Makefile2:1611: tools/CMakeFiles/llvm-slicer.dir/all] Error 2
/usr/bin/ld: CMakeFiles/llvm-cg-dump.dir/llvm-cg-dump.cpp.o: in function `dg::SVFPointerAnalysis::run()':
/home/me/dg/include/dg/llvm/PointerAnalysis/SVFPointerAnalysis.h:183: undefined reference to `SVF::LLVMModuleSet::buildSVFModule(llvm::Module&)'
/usr/bin/ld: CMakeFiles/llvm-cg-dump.dir/llvm-cg-dump.cpp.o: in function `SVF::PointerAnalysis::getPAG() const':
/home/me/SVF/include/MemoryModel/PointerAnalysis.h:196: undefined reference to `SVF::PointerAnalysis::pag'
/usr/bin/ld: CMakeFiles/llvm-cg-dump.dir/llvm-cg-dump.cpp.o: in function `SVF::SymbolTableInfo::getValSym(llvm::Value const*)':
/home/me/SVF/include/SVF-FE/SymbolTableInfo.h:267: undefined reference to `SVF::SymbolTableInfo::isNullPtrSym(llvm::Value const*)'
/usr/bin/ld: /home/me/SVF/include/SVF-FE/SymbolTableInfo.h:269: undefined reference to `SVF::SymbolTableInfo::isBlackholeSym(llvm::Value const*)'
/usr/bin/ld: CMakeFiles/llvm-cg-dump.dir/llvm-cg-dump.cpp.o: in function `SVF::LLVMModuleSet::getLLVMModuleSet()':
/home/me/SVF/include/SVF-FE/LLVMModule.h:69: undefined reference to `SVF::LLVMModuleSet::llvmModuleSet'
/usr/bin/ld: /home/me/SVF/include/SVF-FE/LLVMModule.h:70: undefined reference to `SVF::LLVMModuleSet::llvmModuleSet'
/usr/bin/ld: /home/me/SVF/include/SVF-FE/LLVMModule.h:71: undefined reference to `SVF::LLVMModuleSet::llvmModuleSet'
/usr/bin/ld: CMakeFiles/llvm-cg-dump.dir/llvm-cg-dump.cpp.o: in function `Andersen':
/home/me/SVF/include/WPA/Andersen.h:84: undefined reference to `SVF::BVDataPTAImpl::BVDataPTAImpl(SVF::PAG*, SVF::PointerAnalysis::PTATY, bool)'
/usr/bin/ld: /home/me/SVF/include/WPA/Andersen.h:85: undefined reference to `vtable for SVF::Andersen'
/usr/bin/ld: /home/me/SVF/include/WPA/Andersen.h:85: undefined reference to `vtable for SVF::Andersen'
/usr/bin/ld: CMakeFiles/llvm-cg-dump.dir/llvm-cg-dump.cpp.o: in function `~BVDataPTAImpl':
/home/me/SVF/include/MemoryModel/PointerAnalysisImpl.h:55: undefined reference to `vtable for SVF::BVDataPTAImpl'
/usr/bin/ld: /home/me/SVF/include/MemoryModel/PointerAnalysisImpl.h:57: undefined reference to `SVF::PointerAnalysis::~PointerAnalysis()'
/usr/bin/ld: /home/me/SVF/include/MemoryModel/PointerAnalysisImpl.h:57: undefined reference to `SVF::PointerAnalysis::~PointerAnalysis()'
/usr/bin/ld: CMakeFiles/llvm-cg-dump.dir/llvm-cg-dump.cpp.o: in function `SVF::LLVMModuleSet::releaseLLVMModuleSet()':
/home/me/SVF/include/SVF-FE/LLVMModule.h:76: undefined reference to `SVF::LLVMModuleSet::llvmModuleSet'
/usr/bin/ld: /home/me/SVF/include/SVF-FE/LLVMModule.h:77: undefined reference to `SVF::LLVMModuleSet::llvmModuleSet'
/usr/bin/ld: /home/me/SVF/include/SVF-FE/LLVMModule.h:78: undefined reference to `SVF::LLVMModuleSet::llvmModuleSet'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tools/CMakeFiles/llvm-cg-dump.dir/build.make:110: tools/llvm-cg-dump] Error 1
make[1]: *** [CMakeFiles/Makefile2:1670: tools/CMakeFiles/llvm-cg-dump.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

````

Any help would be appreciated!

**Comment by mchalupa** [comment]
Thanks for the report and the PR draft. I'll check it out.

**Comment by mchalupa** [comment]
It would be helpful to know what cmake command did you use, its output and where do you have the libSvf.a file?

**Comment by mchalupa** [comment]
This is not going to work: https://github.com/mchalupa/dg/compare/master...vwvw:fixes#diff-b3d9a4e0b4696b97512355fbad76887fR184 because _pta is not initialized at that point.

I have fixed the SVF support based on your PR draft (https://github.com/mchalupa/dg/tree/svf-fixes). Do you mind if I push the fixes, or you want to build the fix on your changes?

**Comment by vwvw** [comment]
Push as much as you want, I'm just happy when it resolves ;-) Thanks for the amazing project btw!

**Comment by vwvw** [comment]
The command used for `cmake` is 
`cmake .. -DSVF_DIR=/home/me/SVF/Release-build  `.
I also tried with `-DSVF_INCLUDE)` without more success.

My SVF copy is the [lastest commit](https://github.com/SVF-tools/SVF/tree/ce86d2fccaf19c09eae9d4a974c71836cff78459) and compiled with [`cmake`](https://github.com/svf-tools/SVF/wiki/Setup-Guide#getting-started).

Thanks again!

**Comment by mchalupa** [comment]
Do you have the file `libSvf.a` in `/home/me/SVF/Release-build/lib` ?

**Comment by vwvw** [comment]
Yes I do!

**Comment by mchalupa** [comment]
Good. Could you please try pulling and compiling DG again?

**Comment by vwvw** [comment]
It worked! Thanks for the fix!

**Comment by wliuxingxiangyu** [comment]
@mchalupa 
Hi, thanks for the nice tool!

I used the tool with SVF to point analysis.
I noticed the SVF had updated.
[[include/SVF-FE/PAGBuilder.h → include/SVF-FE/SVFIRBuilder.h]](https://github.com/SVF-tools/SVF/commit/2d3280e35417ec4971e82b0402ee8a5b06e2eb8d#diff-d6ea86f325be7b72d6a6fbab680a83e9e7f40fc4568d924d22a8634b3a2d421a)

So could you help me to update the SVFPointerAnalysis.h in dg ?
 [ #include <SVF-FE/PAGBuilder.h> // PAGBuilder](https://github.com/mchalupa/dg/blob/779cf4dd435cff9c3d39ac4f53db90add85d67db/include/dg/llvm/PointerAnalysis/SVFPointerAnalysis.h#L9)

**Comment by mchalupa** [comment]
@wliuxingxiangyu File a new issue on that, please. I'm not sure how much time I will have to work on this right now, though.

**Comment by wliuxingxiangyu** [comment]
@mchalupa 
Thanks, please go to check the new [issue](https://github.com/mchalupa/dg/issues/447).
