### ISSUE TITLE
Slicing incorrectly hides memory leak

### ISSUE THREAD

**Issue by tomsik68** [mchalupa/dg#345]
Slicing with dg version 8fd2192674b2295881f1cc6f47b1a7d9bad5e7da (which is currently part of Symbiotic) affects verdict of Symbiotic for the following benchmark:
https://github.com/sosy-lab/sv-benchmarks/blob/master/c/memsafety/test-0158-2.c
As far as I can tell, the assignment `data.str.c[1] = sizeof data.str.p1;` which overwrites part of a heap-allocated pointer is sliced away, which should not happen.

**Comment by tomsik68** [comment]
The following program has the same problem without using unions:
```c
int main() {
    void *p = malloc(3U);
    char *a = (char*) p;
    a[1] = 20;
    return 1;
}
```

**Comment by mchalupa** [comment]
Could you check whether the problem is in slicer or in instrumentation? That is, does instrumentation insert the `__INSTR_*` function before the appropriate instruction that should not be sliced away?

**Comment by tomsik68** [comment]
The problem seems to be in instrumentation. Here is the llvm representation of `a[1] = 20;` after instrumentation as produced by Symbiotic:

```llvm
%3 = load i8*, i8** %a, align 4, !dbg !25
%arrayidx = getelementptr inbounds i8, i8* %3, i32 1, !dbg !25
store i8 20, i8* %arrayidx, align 1, !dbg !26
```

I would expect `__INSTR_mark_pointer` before the store, but there is none. The full instrumented source is available at: https://pastebin.com/mn4PMKHP

**Comment by mchalupa** [comment]
Let's move this issue to Symbiotic then.
