### ISSUE TITLE
How to specify the line:variable if I linked multiple bitcode files together?

### ISSUE THREAD

**Issue by Han0nly** [mchalupa/dg#350]
Hi, I'm trying to slice a variable in a cpp project and this project has a lot of files, then I compiled all the files into bitcode and llvm-link them to a single file. So how can I slice a variable using a line:variable cretaria? Can DG analysis a project writen in C++?

Thanks!

**Comment by Han0nly** [comment]
One more question, if DG can deal with CPP projects, then how to slice a member function in a class? e.g. A::B()

**Comment by mchalupa** [comment]
Hi,

> So how can I slice a variable using a line:variable cretaria?

There is now way how to specify the file at the moment. However, if you just specify the line of the original (cpp) file and the variable then it should work (you must compile the files with -g). The disadvantage is that the slicer will try to match this line and variable in _all_ the files, but that is rather unlikely that more files will use a variable of the same name on the same line.

> Can DG analysis a project writen in C++?

The support for C++ is very restricted. Mainly, there is no support for the exceptions, so a C++ project with -fno-exceptions should probably work fine.

>  then how to slice a member function in a class? e.g. A::B()

As dg does not target C++ yet, we have no names demangling, so you must use the mangled name. That is, something like `_ZN1A1BEv` in this case.

**Comment by mchalupa** [comment]
Hi, mater dg now supports specifying also a file in the slicing criterion (if you use the `-sc` option).

**Comment by Han0nly** [comment]
Thanks! That's really helpful, I'll try it as soon as possible.
