### ISSUE TITLE
[Bug?] A simple branch statement

### ISSUE THREAD

**Issue by xfang96** [mchalupa/dg#370]
```C
#include "stdio.h"
#include "assert.h"

int main()
{

    int n, s ;

    scanf("%d", &n);

    if (n > 0)
        s = 1;
    else
        s = -1;

    assert(s > 0);

    return 0;
}
```
When I slice to assert , the slicing result does not include 'scanf' function. Is it a bug?  I think that [assert (s > 0)] depends on the value of n.

**Comment by xfang96** [comment]
Another example:
```
#include "stdio.h"
#include "assert.h"

int main()
{

    int n;
    scanf("%d", &n);

    assert(n > 0);

    return 0;
}
```

The value of n depends on the scanf function, but the result sliced away this input function. I am confused about it.
Looking forward  to your reply. Thanks.

**Comment by xfang96** [comment]
A more general example: 
```C
#include "assert.h"

void change(int* a);

int main()
{
    int a = -1;
    change(&a);            // sliced away

    assert( a > 0);
    
    return 0;
}
```
Sliced away the [change] call-site. In fact , it is possible that the change function will really change the value of a.

**Comment by mchalupa** [comment]
The behavior of external functions may be set using the `-undefined-funs` switch:

```
  --undefined-funs=<value>     - Set the behavior of undefined functions
    =pure                      -   Assume that undefined functions do not read nor write memory
    =write-any                 -   Assume that undefined functions may write any memory
    =read-any                  -   Assume that undefined functions may read any memory
    =rw-any                    -   Assume that undefined functions may read and write any memory
    =write-args                -   Assume that undefined functions may write to arguments
    =read-args                 -   Assume that undefined functions may read from arguments (default)
    =rw-args                   -   Assume that undefined functions may read or write from/to arguments
```

But I should definitely add the model to scanf...

**Comment by xfang96** [comment]
^_^ I got it. It reminds me of the ABI special list of Sanitizers in LLVM. It provides a way to describe the behavior of each undefined function. 
I am reading your thesis. Thanks again.

**Comment by mchalupa** [comment]
>  It reminds me of the ABI special list of Sanitizers in LLVM. It provides a way to describe the behavior of each undefined function.

We've got something similar: https://github.com/mchalupa/dg/blob/master/include/dg/llvm/DataDependence/LLVMDataDependenceAnalysisOptions.h#L22

**Comment by xfang96** [comment]
wow! very nice..

**Comment by xfang96** [comment]
Hello Marel ! Maybe there are some bugs about forward slicing. Could you please fix it?

```C
int source()
{
    return 1;
}

int main()
{
    int test = source();

    int a = 1, b;
    if (a > 1)
        b = 1;
    else
        b = 2;

    return 0;
}
```

forward slicing to source function;
I got some undef value in llvm IR. 

```
llvm-slicer -c source -forward test.ll

define dso_local i32 @source() #0 {
  ret i32 1
}

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @main() #0 {
  %1 = alloca i32, align 4
  %2 = call i32 @source()
  store i32 %2, i32* undef, align 4    ; UNDEF  here
  store i32 1, i32* %1, align 4
  %3 = load i32, i32* %1, align 4
  %4 = icmp sgt i32 %3, 1
  br i1 %4, label %5, label %6

5:                                                ; preds = %0
  store i32 1, i32* undef, align 4    ; UNDEF  here
  br label %safe_return

6:                                                ; preds = %0
  store i32 2, i32* undef, align 4    ; UNDEF  here
  br label %safe_return

safe_return:                                      ; preds = %6, %5
  ret i32 0
}
```
By the way, is forward slicing difficult ?  I mean executable forward slicing result. I didnot find too much paper or discussion about this.
Thanks a lot.

**Comment by mchalupa** [comment]
> Hello Marek ! Maybe there are some bugs about forward slicing. Could you please fix it?

Hi, thanks for the report. We normally don't use forward slicing, so it is not debugged very well. I'll check this.

> By the way, is forward slicing difficult ? I mean executable forward slicing result. I didnot find too much paper or discussion about this.

Actually, I do not know. I implemented it such that I think it should be done to make it executable -- we do the forward slicing to find out what should be In the slice and then we do backward slicing to add instructions that make the slice executable.

**Comment by mchalupa** [comment]
Try the fix in the branch forward-fix, please.

**Comment by xfang96** [comment]
It works,  but it seems a little strange in this way to do the forward slicing. As you said,  just make it executable. I found a slide about forward slicing.  Maybe it is really a difficult question.
[ProgramSlicing.pdf](https://github.com/mchalupa/dg/files/5652822/ProgramSlicing.pdf)    Page.24
What do you think about it?
Thanks again.

**Comment by mchalupa** [comment]
> It works, but it seems a little strange in this way to do the forward slicing.

I do not think it is strange - if you want the slice to be executable, this is the best way how to do that. The backward slice for the forward slice adds precisely the statements that you need to make the slice executable.

**Comment by xfang96** [comment]
Yeah, I agree with you.
