### ISSUE TITLE
  Random code problem

### ISSUE THREAD

**Issue by xiaoxiong007** [mchalupa/dg#371]
hello,

When I use the example, 'clang - C - emit - llvm fact. C - O fact.bc '，

found fact.bc file is garbled, how to deal with this
the fact.bc file like this :

> <90>^T CF<88>¥^@^Y2B^DI^N<90><91>!ÄPAQ<81><8c>á<83>å<8a>^D^YF^FQ^X^@^@<99>^@^@^@^[Ø&øÿÿÿÿ^Ap^@   (^C ^L<88>qx^Gy<90><87>r^X^Gz`<87>|h^Cyx<87>zp^ ...

**Comment by mchalupa** [comment]
If you want to generate readable LLVM IR, you must use `-S` instead of `-c`. Or you use `-c` and disassemble the file with `llvm-dis`.
