### ISSUE TITLE
The dependence graph doesn't have nodes.

### ISSUE THREAD

**Issue by huang429** [mchalupa/dg#421]
Dear Professor ,     
I happen to be doing the work about analysis dependencies between data，and found your awesome job. I have installed the DG environment. I tryed to use the llvm-dg-dump tools，but the graph I received doesn't have any nodes.When I running the tests,the command is 
_./llvm-dg-dump tests/schedule2/schedule2.bc > tests/schedule2/schedule2.dot_
,and the graph is that 
_digraph "DependenceGraph" {
	compound=true label="Graph 0x1105d80 has 77 nodes\n
	dd edges color: cyan4
	use edges color: black, dashed
	cd edges color: blue
	cfg edges color: gray"
}_
Does the tool not work now?Or how should I modify the command?

**Comment by mchalupa** [comment]
Can you provide more information? Are there any error messages? What is the analyzed program?

**Comment by huang429** [comment]
When I input the command ,there isn't any errors.
I use different programs for test.
The program is that,
_#include <assert.h>
#include <stdio.h>
#include <stdlib.h>

long int fact(int x)
{
	long int r = x;
	while (x >= 2){
		x = x - 1;
		r *= x;
	}


	return r;
}

int main(int argc, char **argv)
{
	int a = atoi(argv[1]);
    int b = atoi(argv[2]);
	if(a > 0){
	    printf("fact: %lu\n", fact(b));
	}
	return 0;
}_
And my graph is
_digraph "DependenceGraph" {
	compound=true label="Graph 0x248a5a0 has 26 nodes\n
	dd edges color: cyan4
	use edges color: black, dashed
	cd edges color: blue
	cfg edges color: gray"

}_
I used llvm-6.0.1.I read the DG tools need llvm-3.4 between 3.9,but when I used llvm-3.4,there are errors that "no matching functions from .. to .." during installing the tools.

**Comment by mchalupa** [comment]
This is a bug introduced in bca480ecd5455.

**Comment by huang429** [comment]
> This is a bug introduced in [bca480e](https://github.com/mchalupa/dg/commit/bca480ecd545524befb7bd48d79ee5cbbfe32b02).


Thanks very much.I will try again.
