### ISSUE TITLE
Inconsistency in Slice Output for Switch Statement

### ISSUE THREAD

**Issue by 1TreeForest** [mchalupa/dg#459]
Hello! :) I am trying to do slicing on the following program (a modified version of `tests/slicing/switch1.c`) that contains a switch statement:

```c
int main(void) {
    int a = 5;
    switch (a) {
    case 1:
        a = 4;
        break;
    case 2:
        a = 2;
        break;
    case 3:
        a = 3;
        break;
    case 4:
    case 5:
        a = 8;
        break;
    default:
        a = 3;
    }
    test_assert(a == 8);
    return 0;
}
```
I observed that after using `test-runner-debug.py` (i.e., with the parameter `-c test_assert`), and subsequently applying the `llvm-to-source` tool, the resulting sliced code is as follows:

```c
2: int main(void) {
3:     int a = 5;
4:     switch (a) {
6:         a = 4;
9:         a = 2;
12:         a = 3;
16:         a = 8;
19:         a = 3;
20:     }
22:     test_assert(a == 8);
24: }
```
Despite the fact that the sliced program still outputs the correct result (a equals 8, and I am also confused with this), there seems to be an inconsistency between my expected and the actual output of `llvm-to-source`.

Could you please clarify what might be causing this discrepancy? What should be the correct output of `llvm-to-source` in this case? Thank you!

**Comment by mchalupa** [comment]
Hi, `llvm-to-source` does not produce a syntactically correct programs, it just dumps the lines (and tries to fill in some curly braces) that stayed in the sliced LLVM, see https://github.com/mchalupa/dg/issues/277#issuecomment-499376279

**Comment by 1TreeForest** [comment]
Thanks for the response! I understand that `llvm-to-source` does not produce syntactically correct programs and that there may be some subtle differences in the output. However, the current output discrepancies are too significant. Is this an issue with the specific implementation of `llvm-to-source`? How should it be adjusted for optimization? Can I expect the LLVM bitcode after slicing to be correct, even if the dumped C code is erroneous? Thanks!

**Comment by mchalupa** [comment]
> Is this an issue with the specific implementation of llvm-to-source? How should it be adjusted for optimization?

Yes, this is an issue with the implementation (rather design) of `llvm-to-source`. One way to get better results would be dumping the whole original source code and only highlighting parts of the source code that correspond to preserved instructions (if "only" highlighting is ok for you)

>  Can I expect the LLVM bitcode after slicing to be correct, even if the dumped C code is erroneous?

Yes

**Comment by 1TreeForest** [comment]
Thank you for your answer!
