### ISSUE TITLE
Create simple tutorial

### ISSUE THREAD

**Issue by msoos** [mchalupa/dg#65]
Hey, 

Your project sounds really cool! Can you please give a short example, end-to-end? E.g. how you create the .bc file for a large project, and what do you need to do to build this tool, what software needs to be installed, etc? If you could put that into the README so most people can see it that'd be great.

Thanks!

Mate

**Comment by msoos** [comment]
An example DOT graph would also be pretty useful so I could see what the end result looks like!

**Comment by mchalupa** [comment]
Hey,

I put most of the recommended stuff into README. Instead of .dot file I put there an example of sliced C program (the .dot files are rather long)

If there's something you're missing or anything that you don't like, please tell me (leaving this issue open)

Thanks!
Marek

**Comment by msoos** [comment]
Wow, great job! By the way, as an advice, I personally like to disable the wiki in case the info is mostly in README. Wikis don't tend to get populated or checked out by most people. So information tends to go out-of-date and nobody notices.

Thanks for the great update, looking forward to playing with the tool!

Mate
