### ISSUE TITLE
unify control dependencies in BBlocks

### ISSUE THREAD

**Issue by mchalupa** [mchalupa/dg#98]
we have control deps and we have post-dominator frontiers which are the same in that case. We should probably remove post-dominator frontiers and use only control dependencies.

**Comment by twang15** [comment]
Traditionally, control-dependencies are computed by post-dominator
frontiers.
Are you suggesting using some new algorithm ?

**Comment by mchalupa** [comment]
Yes, reverse post-dominator frontiers are exactly control dependencies. A dependence graph can contain both control dependencies and post-dominator frontiers, and at this moment we use directly post-dominator frontiers while slicing, which is confusing when looking into the code. So I'm suggesting to convert (copy) the post-dominator frontiers into real control dependencies, so that the code is more clear. However, we plan to implement a new method for computation of control dependencies in the future.
